Repository highfidelity/hifi-content, pull requests merged in 2018-10, with the labels that each got.

#199 Whisper Utility
  Prototyping/Domains/Halloween/WhisperInEar/whisperInEar.js
Labels: Dev Approved, QA Approved

#153 Hifi-stubs add
  Utilities/Editor/VSCode_TS-Definitions_Snippets/hifi-vscode.js
  Utilities/Editor/VSCode_TS-Definitions_Snippets/hifiJSDoc.json
  Utilities/Editor/VSCode_TS-Definitions_Snippets/hifiTSStubGenerator.js
  Utilities/Editor/VSCode_TS-Definitions_Snippets/out/hifiStubs.d.ts
  Utilities/Editor/VSCode_TS-Definitions_Snippets/out/hifiVsCode.json
  Utilities/Editor/VSCode_TS-Definitions_Snippets/readme.md
  hifiVsCode.json
  tsconfig.json
  typings/hifi/index.d.ts
Labels: Dev Approved

#169 Rebase DJ-Tools
  DomainContent/Rust/DJ-Tools/DJ-Tools_Personal.js
  DomainContent/Rust/DJ-Tools/DJ-Tools_Spawner.js
  DomainContent/Rust/DJ-Tools/DJ_Dispatch_Zone_Client.js
  DomainContent/Rust/DJ-Tools/DJ_Dispatch_Zone_Server.js
  DomainContent/Rust/DJ-Tools/DJ_Empty_ServerScript.js
  DomainContent/Rust/DJ-Tools/DJ_EndPoint_Light_Server.js
  DomainContent/Rust/DJ-Tools/DJ_EndPoint_Particle_Server.js
  DomainContent/Rust/DJ-Tools/DJ_EndPoint_Sound_Server.js
  DomainContent/Rust/DJ-Tools/DJ_EndPoint_Template_Server.js
  DomainContent/Rust/DJ-Tools/DJ_Generator_Debug_Cube_Client.js
  DomainContent/Rust/DJ-Tools/DJ_Sensor_Box_Client.js
  DomainContent/Rust/DJ-Tools/DJ_Sensor_Template_Client.js
  DomainContent/Rust/DJ-Tools/FlameThrowerBurst.wav
  DomainContent/Rust/DJ-Tools/FlameThrowerRun.wav
  DomainContent/Zaru/applause-app/applause-app.js
  DomainContent/Zaru/applause-app/applause.html
  DomainContent/Zaru/applause-app/loadApplauseApp.js
  DomainContent/Zaru/applause-app/resources/button-pressed.png
  DomainContent/Zaru/applause-app/resources/button.png
  DomainContent/Zaru/applause-app/resources/hand-icon-by-freepik.png
  DomainContent/Zaru/applause-app/resources/hmd-preview-gif.gif
  DomainContent/Zaru/applause-app/sounds/Claps/clap-10.wav
  DomainContent/Zaru/applause-app/sounds/Claps/clap-3.wav
  DomainContent/Zaru/applause-app/sounds/Claps/clap-4.wav
  DomainContent/Zaru/applause-app/sounds/Claps/clap-5.wav
  DomainContent/Zaru/applause-app/sounds/Claps/clap-6.wav
  DomainContent/Zaru/applause-app/sounds/Claps/clap-7.wav
  DomainContent/Zaru/applause-app/sounds/Claps/clap-8.wav
  DomainContent/Zaru/applause-app/sounds/Claps/clap-9.wav
  Utilities/Polyfills.js
  Utilities/readme.md
Labels: Dev Approved, QA Approved

#192 Trivia, Four Square Style
  DomainContent/Trivia/FourSquareTrivia/assets/icons/questionMark-a.png
  DomainContent/Trivia/FourSquareTrivia/assets/icons/questionMark-i.png
  DomainContent/Trivia/FourSquareTrivia/assets/models/highlight.fbx
  DomainContent/Trivia/FourSquareTrivia/assets/sounds/ding.wav
  DomainContent/Trivia/FourSquareTrivia/assets/sounds/timer.wav
  DomainContent/Trivia/FourSquareTrivia/modules/request.js
  DomainContent/Trivia/FourSquareTrivia/trivia.html
  DomainContent/Trivia/FourSquareTrivia/trivia.js
  DomainContent/Trivia/FourSquareTrivia/triviaAvatarCounter.js
  DomainContent/Trivia/FourSquareTrivia/triviaZone.js
Labels: Dev Approved, Experiences, QA Approved

#197 Flashlight spawner
  DomainContent/Halloween/emptyServerScript.js
  DomainContent/Halloween/flashlightSpawner.js
Labels: Dev Approved, Experiences, QA Approved

#203 Digital photo album with readme
  Marketplace/photoFrame/digital-photo-frame.json
  Marketplace/photoFrame/digitalFrame.js
  Marketplace/photoFrame/images/image1.jpg
  Marketplace/photoFrame/images/image2.jpg
  Marketplace/photoFrame/images/image3.jpg
  Marketplace/photoFrame/images/image4.jpg
  Marketplace/photoFrame/images/image5.jpg
  Marketplace/photoFrame/images/keyImage.PNG
  Marketplace/photoFrame/images/userdata.PNG
  Marketplace/photoFrame/readme.md
Labels: Dev Approved, Experiences, QA Approved

#209 Fix lifetime on dishes and plates
  DomainContent/Hub/Space Juice/spaceJuiceSpawner.js
  DomainContent/Hub/plates/ShatterPlatePiece.js
  DomainContent/Hub/plates/ShatterPlateServer.js
Labels: Dev Approved, QA Approved

#208 Fix/flame thrower
  DomainContent/Hub/RainbowThrower/rainbow-gun_fix.json
  DomainContent/Hub/RainbowThrower/scripts/flamethrowerClient.js
Labels: Dev Approved, Experiences, QA Approved

#213 Consolidated halloween content and korea content into proper directories
  DomainContent/Halloween/GifZone/219110__zyrytsounds__evil-laugh.mp3
  DomainContent/Halloween/GifZone/GifZone.js
  DomainContent/Halloween/Spider/HelpMeZone.js
  DomainContent/Halloween/Spider/HelpMeZoneServer.js
  DomainContent/Halloween/Spider/ScaryZone.js
  DomainContent/Halloween/Spider/ScaryZoneServer.js
  DomainContent/Halloween/Spider/resources/help-me-scary.wav
  DomainContent/Halloween/Spider/resources/help-me.wav
  DomainContent/Halloween/WhisperInEar/whisperInEar.js
  DomainContent/Halloween/ZoneStatueJumpScare/zoneStatueJumpScare.js
  DomainContent/Korea/InstrumentSwitch/instrumentSwitch.js
  DomainContent/Korea/Instruments/InstrumentClone.js
  DomainContent/Korea/Instruments/InstrumentSpawner.js
  DomainContent/Korea/Instruments/daegeum/DaegeumClone.js
  DomainContent/Korea/Instruments/daegeum/DaegeumSpawner.js
  DomainContent/Korea/Instruments/daegeum/Sounds/chung_sung_gok_1.wav
  DomainContent/Korea/Instruments/daegeum/Sounds/chung_sung_gok_2.wav
  DomainContent/Korea/Instruments/daegeum/Sounds/chung_sung_gok_3.wav
  DomainContent/Korea/Instruments/daegeum/Sounds/chung_sung_gok_4.wav
  DomainContent/Korea/Instruments/gayageum/GayageumClone.js
  DomainContent/Korea/Instruments/gayageum/GayageumSpawner.js
  DomainContent/Korea/Instruments/gayageum/Sounds/gayageum1.wav
  DomainContent/Korea/Instruments/gayageum/Sounds/gayageum2.wav
  DomainContent/Korea/Instruments/gayageum/Sounds/gayageum3.wav
  DomainContent/Korea/Instruments/janggu/JangguClone.js
  DomainContent/Korea/Instruments/janggu/JangguSpawner.js
  DomainContent/Korea/Instruments/janggu/Sounds/janggu_08_16Bit.wav
  DomainContent/Korea/Instruments/janggu/Sounds/janggu_10_16Bit.wav
  DomainContent/Korea/Instruments/janggu/Sounds/janggu_11_16Bit.wav
Labels: Dev Approved

#212 [WIP] Create readme.md for Halloween domains
  DomainContent/Halloween/readme.md
Labels: Dev Approved, Experiences
