Repository highfidelity/hifi-content, pull requests merged in 2018-05, with the labels that each got.

#121 added Shadow Cascade Indices, Low Normal, and Ambient Occlusion Blur
  DomainContent/Hub/pill/scripts/swallowFXPill.js
Labels: Dev Approved, QA Approved

#101 groupTeleport Tablet App and its Serverless API (AWS)
  Marketplace/groupTeleport/api/index.js
  Marketplace/groupTeleport/api/package.json
  Marketplace/groupTeleport/api/public/client.js
  Marketplace/groupTeleport/api/public/style.css
  Marketplace/groupTeleport/api/serverless.yml
  Marketplace/groupTeleport/api/views/index.html
  Marketplace/groupTeleport/app/group-teleport-a.svg
  Marketplace/groupTeleport/app/group-teleport-i.svg
  Marketplace/groupTeleport/app/groupTeleportApp.html
  Marketplace/groupTeleport/app/groupTeleportApp.js
  Marketplace/groupTeleport/app/modules/request.js
Labels: Dev Approved, QA Approved

#117 Hub domain: Plates
  DomainContent/Hub/plates/ShatterPlateClient.js
  DomainContent/Hub/plates/ShatterPlatePiece.js
  DomainContent/Hub/plates/ShatterPlateServer.js
  DomainContent/Hub/plates/ShatterPlateSpawner.js
  DomainContent/Hub/plates/plate-whole-hub.obj
Labels: Dev Approved, QA Approved

#125 Hub: Flamethrower Shape Ray Cast Fix
  DomainContent/Hub/flamethrower/scripts/flamethrowerClient.js
  DomainContent/Hub/flamethrower/scripts/flamethrowerServer.js
Labels: Dev Approved, QA Approved

#123 Removed broken effects, added spectator camera support to pill
  DomainContent/Hub/pill/scripts/swallowFXPill.js
Labels: Dev Approved, QA Approved

#129 New zombie actor positions
  DomainContent/Zombies/ZombieManager/zombiePositions.js
  DomainContent/Zombies/ZombieManager/zombieStageManager.html
Labels: Dev Approved, QA Approved

#128 Hub: Flamethrower - Normalized ray casts for all
  DomainContent/Hub/flamethrower/scripts/flamethrowerClient.js
Labels: Dev Approved, QA Approved

#130 removed depth, added linear depth
  DomainContent/Hub/pill/scripts/swallowFXPill.js
Labels: Dev Approved, QA Approved

#118 Hub
  DomainContent/Hub/Animation Shower/Models/Shower Head.obj
  DomainContent/Hub/Animation Shower/Models/Shower_Head.mtl
  DomainContent/Hub/Animation Shower/Sounds/animationSwap.wav
  DomainContent/Hub/Animation Shower/Sounds/animationUndo.wav
  DomainContent/Hub/Animation Shower/Sounds/showerMiddle.wav
  DomainContent/Hub/Animation Shower/shower-script.js
  DomainContent/Hub/Animation Shower/showerZoneClient.js
  DomainContent/Hub/Faucets/faucetClient.js
  DomainContent/Hub/Faucets/faucetServer.js
  DomainContent/Hub/Faucets/sounds/faucet.wav
Labels: Dev Approved, QA Approved

#136 small typo fix
  DomainContent/Hub/pill/scripts/swallowFXPill.js
Labels: Dev Approved, QA Approved

#137 Hub Pill comment typo (re-fix)
  DomainContent/Hub/pill/scripts/swallowFXPill.js
Labels: Needs CR

#134 Small fixes for Hub
  DomainContent/Hub/Animation Shower/Models/Shower Head.obj
  DomainContent/Hub/Animation Shower/Models/Shower_Head.mtl
  DomainContent/Hub/Animation Shower/Sounds/animationUndo.wav
  DomainContent/Hub/Animation Shower/Sounds/showerMiddle.wav
  DomainContent/Hub/Animation Shower/Sounds/undo-notif.wav
  DomainContent/Hub/Animation Shower/resetButton.js
  DomainContent/Hub/Animation Shower/shower-script.js
  DomainContent/Hub/Faucets/faucetServer.js
  DomainContent/Hub/plates/ShatterPlatePiece.js
Labels: Dev Approved

#133 Original flamethrower moved to marketplace
  Marketplace/flamethrower/models/flamethrower.mtl
  Marketplace/flamethrower/models/flamethrower.obj
  Marketplace/flamethrower/scripts/flamethrowerClient.js
  Marketplace/flamethrower/scripts/flamethrowerServer.js
  Marketplace/flamethrower/sounds/flamethrowerEndFire.wav
  Marketplace/flamethrower/sounds/flamethrowerEndFire2.wav
  Marketplace/flamethrower/sounds/flamethrowerEndFire3.wav
  Marketplace/flamethrower/sounds/flamethrowerFiring.wav
  Marketplace/flamethrower/textures/desktopFireUnequip.png
  Marketplace/flamethrower/textures/fireball.jpg
Labels: Dev Approved, QA Approved

#82 Drums
  Marketplace/drumKit/DrumKit/COWBELL1.wav
  Marketplace/drumKit/DrumKit/CRASH1.wav
  Marketplace/drumKit/DrumKit/ambient_tom_1.wav
  Marketplace/drumKit/DrumKit/ambient_tom_2.wav
  Marketplace/drumKit/DrumKit/ambient_tom_3.wav
  Marketplace/drumKit/DrumKit/pearlkit-hihat.wav
  Marketplace/drumKit/DrumKit/pearlkit-ride1.wav
  Marketplace/drumKit/DrumKit/pearlkit-ridebell.wav
  Marketplace/drumKit/DrumKit/pearlkit-ridecrash.wav
  Marketplace/drumKit/DrumKit/pearlkit-snare2.wav
  Marketplace/drumKit/cowbell.js
  Marketplace/drumKit/crash.js
  Marketplace/drumKit/floorTom.js
  Marketplace/drumKit/hiHat.js
  Marketplace/drumKit/hitom.js
  Marketplace/drumKit/midTom.js
  Marketplace/drumKit/ride.js
  Marketplace/drumKit/snare.js
Labels: Dev Approved, QA Approved

#85 Guitar
  Marketplace/guitar/attributions.txt
  Marketplace/guitar/guitar.js
  Marketplace/guitar/guitarNeck.js
  Marketplace/guitar/guitarPlay.js
  Marketplace/guitar/guitarZone.js
Labels: Dev Approved

#80 Piano
  Marketplace/Piano/PianoKeys/1.wav
  Marketplace/Piano/PianoKeys/10.wav
  Marketplace/Piano/PianoKeys/11.wav
  Marketplace/Piano/PianoKeys/12.wav
  Marketplace/Piano/PianoKeys/13.wav
  Marketplace/Piano/PianoKeys/14.wav
  Marketplace/Piano/PianoKeys/15.wav
  Marketplace/Piano/PianoKeys/16.wav
  Marketplace/Piano/PianoKeys/17.wav
  Marketplace/Piano/PianoKeys/18.wav
  Marketplace/Piano/PianoKeys/19.wav
  Marketplace/Piano/PianoKeys/2.wav
  Marketplace/Piano/PianoKeys/20.wav
  Marketplace/Piano/PianoKeys/21.wav
  Marketplace/Piano/PianoKeys/22.wav
  Marketplace/Piano/PianoKeys/23.wav
  Marketplace/Piano/PianoKeys/24.wav
  Marketplace/Piano/PianoKeys/25.wav
  Marketplace/Piano/PianoKeys/26.wav
  Marketplace/Piano/PianoKeys/27.wav
  Marketplace/Piano/PianoKeys/28.wav
  Marketplace/Piano/PianoKeys/29.wav
  Marketplace/Piano/PianoKeys/3.wav
  Marketplace/Piano/PianoKeys/30.wav
  Marketplace/Piano/PianoKeys/31.wav
  Marketplace/Piano/PianoKeys/32.wav
  Marketplace/Piano/PianoKeys/33.wav
  Marketplace/Piano/PianoKeys/34.wav
  Marketplace/Piano/PianoKeys/35.wav
  Marketplace/Piano/PianoKeys/36.wav
  Marketplace/Piano/PianoKeys/37.wav
  Marketplace/Piano/PianoKeys/38.wav
  Marketplace/Piano/PianoKeys/39.wav
  Marketplace/Piano/PianoKeys/4.wav
  Marketplace/Piano/PianoKeys/40.wav
  Marketplace/Piano/PianoKeys/41.wav
  Marketplace/Piano/PianoKeys/42.wav
  Marketplace/Piano/PianoKeys/43.wav
  Marketplace/Piano/PianoKeys/44.wav
  Marketplace/Piano/PianoKeys/45.wav
  Marketplace/Piano/PianoKeys/46.wav
  Marketplace/Piano/PianoKeys/47.wav
  Marketplace/Piano/PianoKeys/48.wav
  Marketplace/Piano/PianoKeys/49.wav
  Marketplace/Piano/PianoKeys/5.wav
  Marketplace/Piano/PianoKeys/6.wav
  Marketplace/Piano/PianoKeys/7.wav
  Marketplace/Piano/PianoKeys/8.wav
  Marketplace/Piano/PianoKeys/9.wav
  Marketplace/Piano/PianoKeys/Attributions.txt
  Marketplace/Piano/pianoKey.js
  Marketplace/Piano/pianoKeyboard.js
Labels: Dev Approved

#127 Update to plates
  DomainContent/Hub/plates/ShatterPlateClient.js
  DomainContent/Hub/plates/ShatterPlatePiece.js
  DomainContent/Hub/plates/ShatterPlateServer.js
  DomainContent/Hub/plates/ShatterPlateSpawner.js
  DomainContent/Hub/plates/plate-piece.fbx
  DomainContent/Hub/plates/plate-whole.fbx
  DomainContent/Hub/plates/sound/glass-break1.wav
  DomainContent/Hub/plates/sound/glass-break2.wav
Labels: Dev Approved, QA Approved

#144 Add Spot elevator script into repo
  DomainContent/Hub/utilities/elevator.js
Labels: Dev Approved, Needs CR, QA Approved, QA Ready (internal)

#142 updated to create regular churros and crunch.js sound location
  DomainContent/Mexico/createChurro.js
  DomainContent/Mexico/crunch.js
Labels: Dev Approved, QA Approved

#140 Space Juice Shots
  DomainContent/Hub/Space Juice/animations/Fall.fbx
  DomainContent/Hub/Space Juice/glassPrimitiveCatch.js
  DomainContent/Hub/Space Juice/models/shot-glass-fragment.fbx
  DomainContent/Hub/Space Juice/models/shot-glass.fbx
  DomainContent/Hub/Space Juice/sounds/drink.wav
  DomainContent/Hub/Space Juice/sounds/glassBreaking.wav
  DomainContent/Hub/Space Juice/spaceJuiceClient.js
  DomainContent/Hub/Space Juice/spaceJuiceServer.js
  DomainContent/Hub/Space Juice/spaceJuiceSpawner.js
Labels: Dev Approved, QA Ready (internal)

#143 Entity edit filter for The Spot
  DomainContent/Hub/utilities/filter-spot.js
Labels: Dev Approved

#147 I am a material gun
  DomainContent/Hub/Material Gun/materialGunSpawnerServer.js
  DomainContent/Hub/Material Gun/materialSwapGun.js
  DomainContent/Hub/Material Gun/materialSwapGunServer.js
  DomainContent/Hub/Material Gun/materials/Blue.json
  DomainContent/Hub/Material Gun/materials/Chrome.json
  DomainContent/Hub/Material Gun/materials/Green.json
  DomainContent/Hub/Material Gun/materials/Indigo.json
  DomainContent/Hub/Material Gun/materials/Orange.json
  DomainContent/Hub/Material Gun/materials/Red.json
  DomainContent/Hub/Material Gun/materials/Violet.json
  DomainContent/Hub/Material Gun/materials/Yellow.json
  DomainContent/Hub/Material Gun/models/color-cannon.fbx
  DomainContent/Hub/Material Gun/particles/Bokeh-Particle.png
  DomainContent/Hub/Material Gun/sounds/miss.wav
  DomainContent/Hub/Material Gun/sounds/shoot.wav
  DomainContent/Hub/Material Gun/sounds/swap.wav
  DomainContent/Hub/Material Gun/textures/desktopFireUnequip.png
Labels: Dev Approved
