Repository highfidelity/hifi-content, pull requests merged in 2018-06, with the labels that each got.

#156 Buttons to raise and lower backdrop and web windows for fireside chat
  DomainContent/FiresideChat/buttons/stageManagementButton.js
  DomainContent/FiresideChat/buttons/stageManagementTargetServer.js
Labels: Dev Approved, QA Approved

#155 Made shots not dynamic until grabbed
  DomainContent/Hub/Space Juice/spaceJuiceClient.js
  DomainContent/Hub/Space Juice/spaceJuiceServer.js
  DomainContent/Hub/Space Juice/spaceJuiceSpawner.js
Labels: Dev Approved, QA Approved

#149 Networked facialExpressions
  Prototyping/FacialExpressions/facialExpressions.js
Labels: Dev Approved, QA Approved

#76 Laser pointer
  Marketplace/Laser Pointer/laser.js
  Marketplace/Laser Pointer/models/Glow-ball-red.fbx
  Marketplace/Laser Pointer/models/laser-beam-red.fbx
  Marketplace/Laser Pointer/models/laser-pointer.fbx
  Marketplace/Laser Pointer/models/laser.json
  Marketplace/Laser Pointer/models/light-beam.fbx
  Marketplace/Laser Pointer/sounds/flashlight.wav
  Marketplace/Laser Pointer/sounds/off.wav
  Marketplace/Laser Pointer/sounds/on.wav
Labels: Dev Approved

#159 Applause Application for Zaru
  DomainContent/Zaru/applause-app/applause-app.js
  DomainContent/Zaru/applause-app/applause.html
  DomainContent/Zaru/applause-app/loadApplauseApp.js
  DomainContent/Zaru/applause-app/resources/button-pressed.png
  DomainContent/Zaru/applause-app/resources/button.png
  DomainContent/Zaru/applause-app/resources/hand-icon-by-freepik.png
  DomainContent/Zaru/applause-app/resources/hmd-preview-gif.gif
  DomainContent/Zaru/applause-app/sounds/Claps/clap-10.wav
  DomainContent/Zaru/applause-app/sounds/Claps/clap-3.wav
  DomainContent/Zaru/applause-app/sounds/Claps/clap-4.wav
  DomainContent/Zaru/applause-app/sounds/Claps/clap-5.wav
  DomainContent/Zaru/applause-app/sounds/Claps/clap-6.wav
  DomainContent/Zaru/applause-app/sounds/Claps/clap-7.wav
  DomainContent/Zaru/applause-app/sounds/Claps/clap-8.wav
  DomainContent/Zaru/applause-app/sounds/Claps/clap-9.wav
Labels: Dev Approved, QA Ready
