Repository highfidelity/hifi-content, pull requests merged in 2018-09, with the labels that each got.

#188 Shower Dance Walk Fixes
  DomainContent/Hub/Animation Shower/resetButton.js
  DomainContent/Hub/Animation Shower/shower-script.js
Labels: Dev Approved, Experiences, QA Approved

#191 Shapes app fixes
  Marketplace/shapes/modules/hand.js
  Marketplace/shapes/modules/laser.js
  Marketplace/shapes/shapes.app.json
  Marketplace/shapes/shapes.js
  Marketplace/shapes/utilities/utilities.js
Labels: Dev Approved, Marketplace QA, QA Approved

#186 Meowing Cat
  DomainContent/FaceToFace/Cats/meow.js
  DomainContent/FaceToFace/Cats/resources/sounds/meow.mp3
Labels: Experiences, Needs Code Review, QA Approved

#189 Happy Kiosk with DisplayName
  Prototyping/HappyKiosk/Happy-Kiosk_Zone_Client.js
  Prototyping/HappyKiosk/Happy-Kiosk_Zone_Server.js
Labels: Dev Approved, Experiences, QA Approved

#158 Add latest sit script
  .eslintrc.js
  Prototyping/Sit/sit.js
  Prototyping/Sit/sitServer.js
Labels: Dev Approved, Experiences, QA Approved

#198 integrated pucks patch
  Utilities/Trackers/pucks-sliding-fix.js
Labels: Bug Fix 🐛, Dev Approved, QA Approved

#193 Basic scripts for Halloween domains
  Prototyping/Halloween/219110__zyrytsounds__evil-laugh.mp3
  Prototyping/Halloween/GifZone.js
  Prototyping/Halloween/Spider/HelpMeZone.js
  Prototyping/Halloween/Spider/HelpMeZoneServer.js
  Prototyping/Halloween/Spider/ScaryZone.js
  Prototyping/Halloween/Spider/ScaryZoneServer.js
  Prototyping/Halloween/Spider/resources/help-me-scary.wav
  Prototyping/Halloween/Spider/resources/help-me.wav
Labels: Dev Approved, Experiences, QA Approved

#194 Explosion, following eyes, and random interval sound emitter
  DomainContent/Halloween/ANJExplosion/aNjExplosion.js
  DomainContent/Halloween/ANJExplosion/aNjExplosionServer.js
  DomainContent/Halloween/FollowingEyes/catEyes.js
  DomainContent/Halloween/FollowingEyes/forestEyes.js
  DomainContent/Halloween/SoundEmitterWithRandomInterval/speakerExample.json
  DomainContent/Halloween/SoundEmitterWithRandomInterval/speakerServer.js
  DomainContent/Halloween/models/catEye.fbx
Labels: Dev Approved, Experiences, QA Approved
