Repository highfidelity/hifi-content, pull requests merged in 2018-12, with the labels that each got.

#227 added readMe
  Marketplace/HolidayGun/holidayGun.md
Labels: Dev Approved

#229 Add inspirational quote Marketplace Item
  Marketplace/inspirational-sign/getInspirationalQuoteOfDay.js
  Marketplace/inspirational-sign/readme.md
  Marketplace/inspirational-sign/utils/request.js
Labels: Dev Approved, Experiences, QA Approved

#210 Make Shapes app not grab tablet if editing an entity with hand
  Marketplace/shapes/modules/hand.js
  Marketplace/shapes/shapes.app.json
  Marketplace/shapes/shapes.js
Labels: Dev Approved

#231 Update Readme for Inspirational Sign
  Marketplace/inspirational-sign/readme.md
Labels: Dev Approved

#232 Add primitive painting set to github repo
  Marketplace/primitive-painting/Primitive_Painting_Set.json
  Marketplace/primitive-painting/brushScript.js
  Marketplace/primitive-painting/readme.md
Labels: Dev Approved, QA Approved

#230 Flame thrower fix
  DomainContent/Hub/RainbowThrower/scripts/flamethrowerClient.js
  DomainContent/Hub/RainbowThrower/scripts/rainbowThrowerGunSpawner.js
Labels: Bug Fix 🐛, Dev Approved, Experiences, QA Approved

#238 Added try/catch
  DomainContent/Hub/food/scripts/crunch.js
Labels: Bug Fix 🐛, Dev Approved, Experiences, QA Approved

#237 New Year's Ball Drop
  DomainContent/NewYearBallDrop/assets/audio/auldJimi.mp3
  DomainContent/NewYearBallDrop/assets/audio/explosion.mp3
  DomainContent/NewYearBallDrop/assets/audio/firework.mp3
  DomainContent/NewYearBallDrop/assets/audio/tick.wav
  DomainContent/NewYearBallDrop/assets/audio/tock.wav
  DomainContent/NewYearBallDrop/assets/images/sparkler.jpg
  DomainContent/NewYearBallDrop/ballDrop.js
  DomainContent/NewYearBallDrop/empty.js
Labels: Dev Approved, Experiences, QA Approved

#240 updated all scripts for blueprints
  Marketplace/drumKit/cowbell.js
  Marketplace/drumKit/crash.js
  Marketplace/drumKit/floorTom.js
  Marketplace/drumKit/hiHat.js
  Marketplace/drumKit/hitom.js
  Marketplace/drumKit/midTom.js
  Marketplace/drumKit/ride.js
  Marketplace/drumKit/snare.js
Labels: Dev Approved, Experiences, QA Approved
