Repository highfidelity/hifi-content, pull requests merged in 2018-07, with the labels that each got.

#161 Pucks sliding quick fix
  Utilities/Trackers/pucks-sliding-fix.js
Labels: Dev Approved, QA Approved

#168 Improve the Laser Pointer
  Marketplace/Laser Pointer/laser.js
Labels: Dev Approved, QA Approved, QA Ready (internal)

#164 Bell for jessica
  DomainContent/FaceToFace/Bell/JSON/bell.json
  DomainContent/FaceToFace/Bell/models/bell.fbx
  DomainContent/FaceToFace/Bell/sounds/bell.wav
  DomainContent/FaceToFace/Bell/triggerBell.js
Labels: Dev Approved, QA Ready, QA Ready (internal)

#167 Add app zone util
  Utilities/Zones/AddAppZone.js
Labels: Dev Approved, QA Approved

#174 Raffle Wheel...Spin to Win!
  DomainContent/LoadTest/RaffleWheel/raffleWheel.js
Labels: Dev Approved, QA Approved

#172 Stage manager
  DomainContent/FaceToFace/StageManager/enterStageZone.js
  DomainContent/FaceToFace/StageManager/models/arrow.fbx
  DomainContent/FaceToFace/StageManager/muteTest.js
  DomainContent/FaceToFace/StageManager/screenSetup.html
  DomainContent/FaceToFace/StageManager/sounds/audio1.wav
  DomainContent/FaceToFace/StageManager/sounds/audio2.wav
  DomainContent/FaceToFace/StageManager/stageManager.html
  DomainContent/FaceToFace/StageManager/stageManager.js
  DomainContent/FaceToFace/StageManager/stageManagerTargetServer.js
  DomainContent/FaceToFace/StageManager/svg/megaphone-a.svg
  DomainContent/FaceToFace/StageManager/svg/megaphone-i.svg
Labels: Dev Approved, QA Approved

#171 avatar counter updates by query via domain API
  DomainContent/LoadTest/AvatarCounter/avatarCounter.js
  DomainContent/LoadTest/AvatarCounter/modules/request.js
Labels: Dev Approved, QA Approved

#178 Sync web overlays in stage manager
  DomainContent/FaceToFace/StageManager/stageManager.html
  DomainContent/FaceToFace/StageManager/stageManager.js
  DomainContent/FaceToFace/StageManager/webOverlaySpawner.js
Labels: Dev Approved, QA Ready (internal)

#162 Working V1 Of Kayla Camera
  Prototyping/Kayla-Camera/Kayla-Camera.js
  Prototyping/Kayla-Camera/Polyfills.js
  Prototyping/Kayla-Camera/Tablet/Kayla-Camera-Tablet.html
  Prototyping/Kayla-Camera/Tablet/css/app.css
  Prototyping/Kayla-Camera/Tablet/js/Kayla-Camera-Tablet.js
Labels: Dev Approved, QA Approved

#176 Adding all the scripts used in rust in one place for the origin change…
  DomainContent/Rust/Scripts/Model-Image.js
  DomainContent/Rust/Scripts/ZoneScript.js
  DomainContent/Rust/Scripts/danceScript_no-Right-Click.js
  DomainContent/Rust/Scripts/mirrorClient.js
  DomainContent/Rust/Scripts/noFly.js
  DomainContent/Rust/Scripts/spawnPills.js
  DomainContent/Rust/Scripts/swallowFXPill.js
Labels: Dev Approved
