Repository highfidelity/hifi-content, pull requests merged in 2019-06, with the labels that each got.

#406 Sit
  usefulUtilities/sitV2/README.md
  usefulUtilities/sitV2/appResources/appData/sitClientV2.js
Labels: Dev Approved, QA Approved

#407 DEV-107: Bubble Disabler
  usefulUtilities/bubbleDisabler/README.md
  usefulUtilities/bubbleDisabler/bubbleDisabler.js
Labels: Needs Code Review, QA Approved

#408 Sit
  usefulUtilities/sitV2/README.md
  usefulUtilities/sitV2/appResources/appData/sitClientV2.js
Labels: Bug Fix 🐛, Needs Code Review, QA Approved

#410 DEV-115: WWW/HQ Entity Edit Filters
  domainEntityFilters/www/README.md
  domainEntityFilters/www/filter.js
Labels: Dev Approved, QA Approved

#405 BUGZ-417 +BUGZ-431 White board controller refactor
  usefulUtilities/airAndWhiteboardDraw/README.md
  usefulUtilities/airAndWhiteboardDraw/entityResources/entityClientScripts/drawSphereClient.js
Labels: Dev Approved, QA Approved

#400 BUGZ-268 Google Calendar Integration "v3"
  usefulUtilities/hiFiCalendar/.gitignore
  usefulUtilities/hiFiCalendar/README.md
  usefulUtilities/hiFiCalendar/clientScripts/hiFiCalendar_app.js
  usefulUtilities/hiFiCalendar/clientScripts/meetingRoomSetup_app.js
  usefulUtilities/hiFiCalendar/entities/calendarEntities.json
  usefulUtilities/hiFiCalendar/entities/meetingZone.json
  usefulUtilities/hiFiCalendar/entities/scheduleEntity.json
  usefulUtilities/hiFiCalendar/entities/tokenServer.json
  usefulUtilities/hiFiCalendar/entityScripts/hiFiMeetingZone.js
  usefulUtilities/hiFiCalendar/entityScripts/meetingRoomZone.js
  usefulUtilities/hiFiCalendar/entityServerScripts/clockServer.js
  usefulUtilities/hiFiCalendar/entityServerScripts/hiFiCalendarServer.js
  usefulUtilities/hiFiCalendar/entityServerScripts/occupantsServer.js
  usefulUtilities/hiFiCalendar/entityServerScripts/roomScheduleServer.js
  usefulUtilities/hiFiCalendar/entityServerScripts/tokenServer.js
  usefulUtilities/hiFiCalendar/hifiWebApp/.gitignore
  usefulUtilities/hiFiCalendar/hifiWebApp/hifiCalendarRouter.js
  usefulUtilities/hiFiCalendar/hifiWebApp/hifiCalendarServer.js
  usefulUtilities/hiFiCalendar/hifiWebApp/package-lock.json
  usefulUtilities/hiFiCalendar/hifiWebApp/package.json
  usefulUtilities/hiFiCalendar/hifiWebApp/public/css/styles.css
  usefulUtilities/hiFiCalendar/hifiWebApp/public/js/meetingRoom_ui.js
  usefulUtilities/hiFiCalendar/hifiWebApp/public/meetingRoom_ui.html
  usefulUtilities/hiFiCalendar/hifiWebApp/public/resources/fonts/Graphik-Regular.woff
  usefulUtilities/hiFiCalendar/hifiWebApp/public/resources/fonts/Graphik-Semibold.woff
  usefulUtilities/hiFiCalendar/hifiWebApp/public/resources/images/BottomLeftCorner_Shard.png
  usefulUtilities/hiFiCalendar/hifiWebApp/public/resources/images/TopRightCorner_Shard.png
  usefulUtilities/hiFiCalendar/hifiWebApp/public/resources/images/arrow.png
  usefulUtilities/hiFiCalendar/hifiWebApp/public/resources/images/btn_google_signin_dark_disabled_web@2x.png
  usefulUtilities/hiFiCalendar/hifiWebApp/public/resources/images/btn_google_signin_dark_focus_web@2x.png
  usefulUtilities/hiFiCalendar/hifiWebApp/public/resources/images/btn_google_signin_dark_normal_web@2x.png
  usefulUtilities/hiFiCalendar/hifiWebApp/public/resources/images/btn_google_signin_dark_pressed_web@2x.png
  usefulUtilities/hiFiCalendar/hifiWebApp/public/resources/images/edit.png
  usefulUtilities/hiFiCalendar/hifiWebApp/public/resources/images/trash.png
  usefulUtilities/hiFiCalendar/hifiWebApp/public/resources/images/voxel-loader.png
  usefulUtilities/hiFiCalendar/localHTTP/hiFiCalendar.html
  usefulUtilities/hiFiCalendar/resources/images/CALENDAR-a.svg
  usefulUtilities/hiFiCalendar/resources/images/CALENDAR-i.svg
  usefulUtilities/hiFiCalendar/resources/images/calendar-a.svg
  usefulUtilities/hiFiCalendar/resources/images/calendar-i.svg
  usefulUtilities/hiFiCalendar/resources/modules/request.js
Labels: Dev Approved, QA Approved

#411 Whiteboard
  usefulUtilities/airAndWhiteboardDraw/README.md
  usefulUtilities/airAndWhiteboardDraw/entityResources/entityClientScripts/drawSphereClient.js
Labels: Bug Fix 🐛, Dev Approved, QA Approved

#412 BUGZ 653 :: Calendar encodeURI fix
  usefulUtilities/hiFiCalendar/README.md
  usefulUtilities/hiFiCalendar/entityServerScripts/roomScheduleServer.js
Labels: Dev Approved, QA Approved

#413 Sit
  usefulUtilities/sitV2/README.md
  usefulUtilities/sitV2/appResources/appData/sitClientV2.js
Labels: Bug Fix 🐛, Dev Approved, QA Approved

#414 Better Portal bookmarks
  usefulUtilities/portal/README.md
  usefulUtilities/portal/portal.js
Labels: Dev Approved, QA Approved

#415 Dev-70 :: Ui fix
  usefulUtilities/hiFiCalendar/README.md
  usefulUtilities/hiFiCalendar/hifiWebApp/public/css/styles.css
  usefulUtilities/hiFiCalendar/hifiWebApp/public/js/meetingRoom_ui.js
  usefulUtilities/hiFiCalendar/hifiWebApp/public/meetingRoom_ui.html
  usefulUtilities/hiFiCalendar/hifiWebApp/public/resources/images/loadingSpinner.svg
Labels: Dev Approved, QA Approved

#416 DEV-143: Drawing In Air
  usefulUtilities/airAndWhiteboardDraw/README.md
  usefulUtilities/airAndWhiteboardDraw/entityResources/entityClientScripts/drawSphereClient.js
Labels: Dev Approved, QA Ready (internal)

#418 Jira 575 Sit - In HMD Going From one Sit Cube to another straightens legs
  usefulUtilities/sitV2/README.md
  usefulUtilities/sitV2/appResources/appData/sitClientV2.js
Labels: Bug Fix 🐛, Dev Approved, QA Approved

#419 BUGZ-576: Removing Logspam on sit
  usefulUtilities/sitV2/README.md
  usefulUtilities/sitV2/appResources/appData/sitClientV2.js
Labels: Dev Approved, QA Approved

#421 [Bugz 773] - Sit floor bug small bump fix
  usefulUtilities/sitV2/README.md
  usefulUtilities/sitV2/appResources/appData/sitClientV2.js
Labels: Dev Approved, QA Approved

#420 [Bugz-769] :: Cal app new intro
  usefulUtilities/hiFiCalendar/README.md
  usefulUtilities/hiFiCalendar/hifiWebApp/public/css/styles.css
  usefulUtilities/hiFiCalendar/hifiWebApp/public/js/meetingRoom_ui.js
  usefulUtilities/hiFiCalendar/hifiWebApp/public/meetingRoom_ui.html
Labels: Needs Code Review, QA Approved

#422 DEV-169: Create a script that auto-changes the URL of the Directory web entity
  usefulUtilities/statusIndicator/README.md
  usefulUtilities/statusIndicator/hifiScript/directoryClientScript/directoryClientScript.js
Labels: Dev Approved, QA Approved

#424 Calendar JSON
  usefulUtilities/hiFiCalendar/entities/calendarEntities.json
Labels: Bug Fix 🐛, Dev Approved, Needs Code Review, QA Approved

#425 calendar
  usefulUtilities/hiFiCalendar/README.md
Labels: Dev Approved, QA Approved

#426 [Bugz-822] and [Bugz-708] Cal link fix / Spam log fix
  usefulUtilities/hiFiCalendar/README.md
  usefulUtilities/hiFiCalendar/clientScripts/externalQMLInfo.qml
  usefulUtilities/hiFiCalendar/clientScripts/meetingRoomSetup_app.js
  usefulUtilities/hiFiCalendar/entities/calendarEntities.json
  usefulUtilities/hiFiCalendar/entities/tokenServer.json
  usefulUtilities/hiFiCalendar/entityServerScripts/roomScheduleServer.js
  usefulUtilities/hiFiCalendar/hifiWebApp/public/js/meetingRoom_ui.js
Labels: Dev Approved, QA Approved

#429 DEV-181: Move Spectator Camera, Tablet Cam, and RPO360 resources
  marketplaceItems/RPO360/App Resources/RPO360.app.json
  marketplaceItems/RPO360/App Resources/appData/RPO360.js
  marketplaceItems/RPO360/App Resources/appData/RPO360.qml
  marketplaceItems/RPO360/App Resources/appData/resources/images/icons/rpo360-a.svg
  marketplaceItems/RPO360/App Resources/appData/resources/images/icons/rpo360-i.svg
  marketplaceItems/RPO360/App Resources/appData/resources/images/processing.gif
  marketplaceItems/RPO360/App Resources/appData/resources/images/static.gif
  marketplaceItems/RPO360/App Resources/appData/resources/models/invertedSphere.fbx
  marketplaceItems/RPO360/App Resources/appData/resources/models/rpo360.fbx
  marketplaceItems/RPO360/App Resources/appData/resources/sounds/cameraOn.wav
  marketplaceItems/RPO360/App Resources/appData/resources/sounds/snap.wav
  marketplaceItems/RPO360/Marketplace Resources/Marketplace Item Data.txt
  marketplaceItems/RPO360/Marketplace Resources/RPO360.png
  marketplaceItems/spectatorCamera/Description.txt
  marketplaceItems/spectatorCamera/Spectator Camera Marketplace Image.jpg
  marketplaceItems/spectatorCamera/SpectatorCamera.qml
  marketplaceItems/spectatorCamera/cameraOn.wav
  marketplaceItems/spectatorCamera/flashOff.wav
  marketplaceItems/spectatorCamera/flashOn.wav
  marketplaceItems/spectatorCamera/processing.gif
  marketplaceItems/spectatorCamera/snap.wav
  marketplaceItems/spectatorCamera/spectator-camera.fbx
  marketplaceItems/spectatorCamera/spectatorCamera.app.json
  marketplaceItems/spectatorCamera/spectatorCamera.js
  marketplaceItems/spectatorCamera/static.gif
  marketplaceItems/tabletCam/README.md
  marketplaceItems/tabletCam/appData/ui/TabletCam.qml
  marketplaceItems/tabletCam/marketplaceData/Marketplace Description.md
  marketplaceItems/tabletCam/tabletCam.app.json
Labels: Dev Approved, QA Approved

#430 BUGZ-849 Fix avatar unable to move if server restarts while sitting
  usefulUtilities/sitV2/appResources/appData/sitClientV2.js
Labels: Bug Fix 🐛, Dev Approved, QA Approved

#427 Sit animation fix
  usefulUtilities/sitV2/README.md
  usefulUtilities/sitV2/appResources/appData/sitClientV2.js
Labels: Dev Approved, QA Approved
