Repository highfidelity/hifi-content, pull requests merged in 2019-04, with the labels that each got.

#337 High Fidelity Push system
  usefulUtilities/hifiPing/.gitignore
  usefulUtilities/hifiPing/README.md
  usefulUtilities/hifiPing/hifiApp/assets/icons/ping-a.svg
  usefulUtilities/hifiPing/hifiApp/assets/icons/ping-i.svg
  usefulUtilities/hifiPing/hifiApp/ping_app.js
  usefulUtilities/hifiPing/hifiApp/ui/css/ping_ui.css
  usefulUtilities/hifiPing/hifiApp/ui/images/loadingSpinner.svg
  usefulUtilities/hifiPing/hifiApp/ui/js/ping_ui.js
  usefulUtilities/hifiPing/hifiApp/ui/ping_ui.html
  usefulUtilities/hifiPing/webApp/app/package-lock.json
  usefulUtilities/hifiPing/webApp/app/package.json
  usefulUtilities/hifiPing/webApp/app/pingServer.js
  usefulUtilities/hifiPing/webApp/www/hifiPing/css/index.css
  usefulUtilities/hifiPing/webApp/www/hifiPing/images/hifi.png
  usefulUtilities/hifiPing/webApp/www/hifiPing/index.html
  usefulUtilities/hifiPing/webApp/www/hifiPing/js/ping.js
  usefulUtilities/hifiPing/webApp/www/hifiPing/service-worker.js
Labels: Dev Approved, QA Approved

#340 User Location Banner
  usefulUtilities/userLocation/README.md
  usefulUtilities/userLocation/modules/request.js
  usefulUtilities/userLocation/userLocation.js
  usefulUtilities/userLocation/userLocation.json
  usefulUtilities/userLocation/userLocationTextLocalEntity.js
Labels: Dev Approved, QA Approved

#343 User inspector81 update
  marketplaceItems/userInspector/README.md
  marketplaceItems/userInspector/appResources/appData/resources/modules/defaultLocalEntityProps.js
  marketplaceItems/userInspector/appResources/appData/resources/modules/nameTagListManager.js
  marketplaceItems/userInspector/appResources/appData/resources/modules/pickRayController.js
  marketplaceItems/userInspector/appResources/appData/resources/userInspector_ui.html
  marketplaceItems/userInspector/appResources/userInspector.app.json
  marketplaceItems/userInspector/marketplaceResources/Description.md
Labels: Dev Approved, QA Approved

#339 Status indicator
  usefulUtilities/statusIndicator/.gitignore
  usefulUtilities/statusIndicator/README.md
  usefulUtilities/statusIndicator/hifiScript/statusIndicator.js
  usefulUtilities/statusIndicator/webApp/app/package-lock.json
  usefulUtilities/statusIndicator/webApp/app/package.json
  usefulUtilities/statusIndicator/webApp/app/statusIndicator_webApp.js
  usefulUtilities/statusIndicator/webApp/www/allEmployees.html
  usefulUtilities/statusIndicator/webApp/www/teamPage.html
Labels: Dev Approved, QA Approved

#344 Status Indicator Improvements
  usefulUtilities/statusIndicator/README.md
  usefulUtilities/statusIndicator/hifiScript/statusIndicator.js
  usefulUtilities/statusIndicator/webApp/app/statusIndicator_webApp.js
  usefulUtilities/statusIndicator/webApp/www/teamPage.html
Labels: Dev Approved, QA Approved

#347 added location to status indicator and zone script
  usefulUtilities/statusIndicator/README.md
  usefulUtilities/statusIndicator/hifiScript/statusIndicator.js
  usefulUtilities/statusIndicator/hifiScript/zoneEntityScripts/locationZoneClient.js
  usefulUtilities/statusIndicator/webApp/app/statusIndicator_webApp.js
  usefulUtilities/statusIndicator/webApp/www/teamPage.html
Labels: Needs Code Review, QA Ready

#352 Appreciate App v1.5
  marketplaceItems/appreciate/README.md
  marketplaceItems/appreciate/appResources/appData/appreciate_app.js
  marketplaceItems/appreciate/appResources/appData/resources/appreciate_ui.html
  marketplaceItems/appreciate/marketplaceResources/description.md
Labels: Dev Approved, QA Approved

#346 Office Mat v1.0
  usefulUtilities/officeMat/.gitignore
  usefulUtilities/officeMat/README.md
  usefulUtilities/officeMat/entityScripts/zones/squareZone.js
  usefulUtilities/officeMat/officeMat.json
Labels: Needs Code Review, QA Approved

#355 New statusIndicator HTML and API updates
  usefulUtilities/statusIndicator/README.md
  usefulUtilities/statusIndicator/webApp/app/statusIndicator_webApp.js
  usefulUtilities/statusIndicator/webApp/www/allEmployees.html
  usefulUtilities/statusIndicator/webApp/www/css/index.css
  usefulUtilities/statusIndicator/webApp/www/teamPage.html
Labels: Needs Code Review, QA Approved

#357 Vending Machine v2
  marketplaceItems/vendingMachine/README.md
  marketplaceItems/vendingMachine/entityResources/entity/vendingMachine.json
  marketplaceItems/vendingMachine/entityResources/entityClientScripts/vendingMachineButton.js
  marketplaceItems/vendingMachine/entityResources/entityClientScripts/vendingMachineItems.json
  marketplaceItems/vendingMachine/marketplaceResources/Description.md
Labels: Dev Approved, QA Approved

#356 Web app express template
  usefulUtilities/webAppTemplate/.gitignore
  usefulUtilities/webAppTemplate/README.md
  usefulUtilities/webAppTemplate/dbClass.js
  usefulUtilities/webAppTemplate/dbMaker.js
  usefulUtilities/webAppTemplate/package-lock.json
  usefulUtilities/webAppTemplate/package.json
  usefulUtilities/webAppTemplate/webRouter.js
  usefulUtilities/webAppTemplate/webServer.js
Labels: Needs Code Review, QA Approved

#364 Fix/user inspector meshpick
  marketplaceItems/userInspector/README.md
  marketplaceItems/userInspector/appResources/appData/resources/modules/nameTagListManager.js
  marketplaceItems/userInspector/appResources/appData/resources/userInspector_ui.html
  marketplaceItems/userInspector/marketplaceResources/Description.md
Labels: Needs Code Review, QA Approved

#362 Add client entity dev reference script
  developerTools/scriptReferences/entityClientScript/README.md
  developerTools/scriptReferences/entityClientScript/entityClientScript.js
Labels: Dev Approved

#360 Fix click to sit bug
  marketplaceItems/sitPoint/README.md
  marketplaceItems/sitPoint/appResources/appData/sitClient.js
  marketplaceItems/sitPoint/appResources/appData/sitServer.js
Labels: Legacy code, Needs Code Review, QA Approved

#354 Unmute zone
  usefulUtilities/unmuteZone/README.md
  usefulUtilities/unmuteZone/unmuteZoneClient.js
Labels: Needs Code Review, QA Approved

#353 Whiteboard Draw Combo
  usefulUtilities/airAndWhiteboardDraw/2019-04-18_09-44-00/README.md
  usefulUtilities/airAndWhiteboardDraw/2019-04-18_09-44-00/entityResources/entity/whiteboard.json
  usefulUtilities/airAndWhiteboardDraw/2019-04-18_09-44-00/entityResources/entityClientScripts/drawSphereClient.js
  usefulUtilities/airAndWhiteboardDraw/2019-04-18_09-44-00/entityResources/entityClientScripts/drawSphereSpawnerClient.js
  usefulUtilities/airAndWhiteboardDraw/2019-04-18_09-44-00/entityResources/entityClientScripts/whiteboardReset.js
  usefulUtilities/airAndWhiteboardDraw/2019-04-18_09-44-00/entityResources/entityClientScripts/whiteboardZoneClient.js
  usefulUtilities/airAndWhiteboardDraw/2019-04-18_09-44-00/entityResources/resources/models/sphere-white-emissive.fbx
  usefulUtilities/airAndWhiteboardDraw/2019-04-18_09-44-00/entityResources/resources/sounds/close.mp3
  usefulUtilities/airAndWhiteboardDraw/2019-04-18_09-44-00/entityResources/resources/sounds/draw.mp3
  usefulUtilities/airAndWhiteboardDraw/2019-04-18_09-44-00/entityResources/resources/sounds/open.mp3
  usefulUtilities/airAndWhiteboardDraw/2019-04-18_09-44-00/entityResources/resources/sounds/resetWhiteboard.mp3
  usefulUtilities/airAndWhiteboardDraw/2019-04-18_09-44-00/entityResources/resources/textures/black.png
  usefulUtilities/airAndWhiteboardDraw/2019-04-18_09-44-00/entityResources/resources/textures/blue.png
  usefulUtilities/airAndWhiteboardDraw/2019-04-18_09-44-00/entityResources/resources/textures/cyan.png
  usefulUtilities/airAndWhiteboardDraw/2019-04-18_09-44-00/entityResources/resources/textures/green.png
  usefulUtilities/airAndWhiteboardDraw/2019-04-18_09-44-00/entityResources/resources/textures/magenta.png
  usefulUtilities/airAndWhiteboardDraw/2019-04-18_09-44-00/entityResources/resources/textures/neutral1.png
  usefulUtilities/airAndWhiteboardDraw/2019-04-18_09-44-00/entityResources/resources/textures/neutral2.png
  usefulUtilities/airAndWhiteboardDraw/2019-04-18_09-44-00/entityResources/resources/textures/neutral3.png
  usefulUtilities/airAndWhiteboardDraw/2019-04-18_09-44-00/entityResources/resources/textures/neutral4.png
  usefulUtilities/airAndWhiteboardDraw/2019-04-18_09-44-00/entityResources/resources/textures/red.png
  usefulUtilities/airAndWhiteboardDraw/2019-04-18_09-44-00/entityResources/resources/textures/yellow.png
Labels: Experiences, Needs Code Review, QA Approved

#361 HiFi Calendar V2
  usefulUtilities/hiFiCalendar/README.md
  usefulUtilities/hiFiCalendar/clientScripts/hiFiCalendar_app.js
  usefulUtilities/hiFiCalendar/entities/meetingZone.json
  usefulUtilities/hiFiCalendar/entities/scheduleEntity.json
  usefulUtilities/hiFiCalendar/entityScripts/hiFiMeetingZone.js
  usefulUtilities/hiFiCalendar/entityServerScripts/clockServer.js
  usefulUtilities/hiFiCalendar/entityServerScripts/hiFiCalendarServer.js
  usefulUtilities/hiFiCalendar/entityServerScripts/noFunction.js
  usefulUtilities/hiFiCalendar/localHTTP/hiFiCalendar.html
  usefulUtilities/hiFiCalendar/resources/hiFiCalendar.html
  usefulUtilities/hiFiCalendar/resources/modules/request.js
Labels: Dev Approved, QA Approved

#367 Status Indicator: A fresh new Directory look!
  usefulUtilities/statusIndicator/README.md
  usefulUtilities/statusIndicator/webApp/www/allEmployees.html
  usefulUtilities/statusIndicator/webApp/www/css/index.css
  usefulUtilities/statusIndicator/webApp/www/js/formatStatusData.js
  usefulUtilities/statusIndicator/webApp/www/teamPage.html
Labels: Dev Approved, QA Approved

#368 Spinnable Wheel
  usefulUtilities/spinnableWheel/README.md
  usefulUtilities/spinnableWheel/spinnableWheel.json
  usefulUtilities/spinnableWheel/spinnableWheelClient.js
  usefulUtilities/spinnableWheel/spinnableWheelServer.js
Labels: Needs Code Review, QA Approved

#370 Fix off-axis spinnable wheel
  usefulUtilities/spinnableWheel/README.md
  usefulUtilities/spinnableWheel/spinnableWheel.json
  usefulUtilities/spinnableWheel/spinnableWheelServer.js
Labels: Needs Code Review, QA Approved

#371 Directory Page - Slight UI Refresh
  usefulUtilities/statusIndicator/README.md
  usefulUtilities/statusIndicator/webApp/www/css/index.css
  usefulUtilities/statusIndicator/webApp/www/js/formatStatusData.js
Labels: Needs Code Review, QA Approved

#373 Unmute Zone: HALF fix
  usefulUtilities/unmuteZone/README.md
  usefulUtilities/unmuteZone/unmuteZoneClient.js
Labels: Needs Code Review, QA Approved

#377 Status indicator update unknown to online
  usefulUtilities/statusIndicator/webApp/www/js/formatStatusData.js
Labels: Dev Approved, QA Ready (internal)
