Repository highfidelity/hifi-content, pull requests merged in 2019-05, with the labels that each got.

#379 Script Pauser: Username Whitelist
  usefulUtilities/scriptPauser/README.md
  usefulUtilities/scriptPauser/scriptPauser.js
Labels: Needs Code Review, QA Approved

#386 Sit
  usefulUtilities/sitV2/README.md
  usefulUtilities/sitV2/appResources/appData/resources/animations/sittingIdle.fbx
  usefulUtilities/sitV2/appResources/appData/resources/canSitZoneClient.js
  usefulUtilities/sitV2/appResources/appData/resources/images/clickToSit.png
  usefulUtilities/sitV2/appResources/appData/resources/images/holdToStandUp.png
  usefulUtilities/sitV2/appResources/appData/resources/images/presit/pleaseFaceForward.png
  usefulUtilities/sitV2/appResources/appData/resources/images/presit/sitConfirm1.png
  usefulUtilities/sitV2/appResources/appData/resources/images/presit/sitConfirm10.png
  usefulUtilities/sitV2/appResources/appData/resources/images/presit/sitConfirm11.png
  usefulUtilities/sitV2/appResources/appData/resources/images/presit/sitConfirm12.png
  usefulUtilities/sitV2/appResources/appData/resources/images/presit/sitConfirm2.png
  usefulUtilities/sitV2/appResources/appData/resources/images/presit/sitConfirm3.png
  usefulUtilities/sitV2/appResources/appData/resources/images/presit/sitConfirm4.png
  usefulUtilities/sitV2/appResources/appData/resources/images/presit/sitConfirm5.png
  usefulUtilities/sitV2/appResources/appData/resources/images/presit/sitConfirm6.png
  usefulUtilities/sitV2/appResources/appData/resources/images/presit/sitConfirm7.png
  usefulUtilities/sitV2/appResources/appData/resources/images/presit/sitConfirm8.png
  usefulUtilities/sitV2/appResources/appData/resources/images/presit/sitConfirm9.png
  usefulUtilities/sitV2/appResources/appData/resources/images/triggerToSit.png
  usefulUtilities/sitV2/appResources/appData/resources/sittableUIClient.js
  usefulUtilities/sitV2/appResources/appData/sitClientV2.js
  usefulUtilities/sitV2/appResources/appData/sitServerV2.js
Labels: Dev Approved, QA Approved

#388 Sit Rotation Value Fix
  usefulUtilities/sitV2/README.md
  usefulUtilities/sitV2/appResources/appData/sitClientV2.js
Labels: QA Approved

#389 App loader: quick fix
  usefulUtilities/appLoader/README.md
  usefulUtilities/appLoader/appLoader.js
Labels: Needs Code Review, QA Approved

#390 App Loader whitelist
  usefulUtilities/appLoader/README.md
  usefulUtilities/appLoader/appLoader.js
Labels: Needs Code Review, QA Approved

#391 Status Indicator Upgrade and Bug Fixes
  usefulUtilities/statusIndicator/README.md
  usefulUtilities/statusIndicator/hifiScript/statusIndicator.js
  usefulUtilities/statusIndicator/hifiScript/zoneEntityScripts/locationZoneClient.js
  usefulUtilities/statusIndicator/webApp/app/statusIndicator_webApp.js
  usefulUtilities/statusIndicator/webApp/www/allEmployees.html
  usefulUtilities/statusIndicator/webApp/www/js/formatStatusData.js
  usefulUtilities/statusIndicator/webApp/www/teamPage.html
Labels: Dev Approved, QA Ready (internal)

#392 Sit bugs
  usefulUtilities/sitV2/README.md
  usefulUtilities/sitV2/appResources/appData/sitServerV2.js
Labels: Dev Approved, QA Approved

#394 Whiteboard bugs
  usefulUtilities/airAndWhiteboardDraw/README.md
  usefulUtilities/airAndWhiteboardDraw/entityResources/entityClientScripts/drawSphereClient.js
  usefulUtilities/airAndWhiteboardDraw/entityResources/entityClientScripts/drawSphereSpawnerClient.js
Labels: Bug Fix 🐛, Needs Code Review, QA Ready (internal)

#393 Sit Bug 259
  usefulUtilities/sitV2/README.md
  usefulUtilities/sitV2/appResources/appData/sitClientV2.js
Labels: Needs Code Review, QA Approved

#395 Spawn point zone
  usefulUtilities/spawnPointZone/README.md
  usefulUtilities/spawnPointZone/entityResources/entityClientScripts/spawnPointZone.js
Labels: Bug Fix 🐛, Needs Code Review, QA Approved

#397 Sit Bug 307
  usefulUtilities/sitV2/README.md
  usefulUtilities/sitV2/appResources/appData/sitClientV2.js
  usefulUtilities/sitV2/appResources/appData/sitServerV2.js
Labels: Bug Fix 🐛, Needs Code Review, QA Approved

#396 Spawn Point Zone Bugs 314 and 315
  usefulUtilities/spawnPointZone/README.md
  usefulUtilities/spawnPointZone/entityResources/entityClientScripts/spawnPointZone.js
Labels: Bug Fix 🐛, Dev Approved, QA Approved

#399 Sit cube bug
  usefulUtilities/sitV2/README.md
  usefulUtilities/sitV2/appResources/appData/sitClientV2.js
  usefulUtilities/sitV2/appResources/appData/sitServerV2.js
Labels: Bug Fix 🐛, Needs Code Review, QA Approved

#398 New Portal
  usefulUtilities/portal/README.md
  usefulUtilities/portal/portal.js
Labels: Dev Approved, QA Approved

#402 Clock
  usefulUtilities/clock/README.md
  usefulUtilities/clock/entityResources/clockServer.js
Labels: Dev Approved, QA Approved

#404 Add Home bookmark support to Portal script
  usefulUtilities/portal/README.md
  usefulUtilities/portal/portal.js
Labels: Dev Approved

#403 Implement canary endpoint for status indicator
  usefulUtilities/statusIndicator/.gitignore
  usefulUtilities/statusIndicator/README.md
  usefulUtilities/statusIndicator/webApp/app/package-lock.json
  usefulUtilities/statusIndicator/webApp/app/package.json
  usefulUtilities/statusIndicator/webApp/app/statusIndicator_webApp.js
Labels: Dev Approved
