Repository highfidelity/hifi-content, pull requests merged in 2019-10, with the labels that each got.

#467 Sit Scripts: Hopeful fix for DEV-2283 and DEV-2269
  usefulUtilities/sit/README.md
  usefulUtilities/sit/resources/sittableUIClient.js
  usefulUtilities/sit/sitClient.js
  usefulUtilities/sit/sitServer.js
Labels: Dev Approved, QA Approved

#468 DEV-2303: Fix another bug that prevents people from sitting
  usefulUtilities/sit/README.md
  usefulUtilities/sit/sitClient.js
Labels: Dev Approved

#469 Fix for chatterbox sounds sometimes missing on server restart
  placeSpecificContent/hq/chatterboxes/chatterbox/buttons/privacyButton_server.js
Labels: Bug Fix 🐛, Dev Approved, QA Approved

#471 Chatterbox fixes
  placeSpecificContent/hq/chatterboxes/README.md
Labels: Needs Code Review
