Repository highfidelity/hifi-content, pull requests merged in 2019-08, with the labels that each got.

#445 BUGZ-1125: Mirror entity should not be grabbable
  usefulUtilities/mirror/README.md
  usefulUtilities/mirror/mirrorClient.js
Labels: Dev Approved

#446 Fix BUGZ-1147: Audio log spam when in serverless domain
  usefulUtilities/soundEmitter/README.md
  usefulUtilities/soundEmitter/soundEmitter.js
Labels: Dev Approved, QA Approved

#447 BUGZ 1159- Whiteboards can erase lines on other whiteboards if in close proximity
  usefulUtilities/airAndWhiteboardDraw/README.md
  usefulUtilities/airAndWhiteboardDraw/entityResources/entityClientScripts/drawSphereClient.js
  usefulUtilities/airAndWhiteboardDraw/entityResources/entityClientScripts/whiteboardReset.js
Labels: Bug Fix 🐛, Experiences, Needs Code Review, QA Ready (internal)

#449 DEV-345: Sit V2.5
  usefulUtilities/sitV2/README.md
  usefulUtilities/sitV2/appResources/appData/resources/sittableUIClient.js
  usefulUtilities/sitV2/appResources/appData/sitClientV2.js
  usefulUtilities/sitV2/appResources/appData/sitServerV2.js
Labels: Dev Approved, QA Ready

#452 New request.js module again!
  modules/request/README.md
  modules/request/request.js
Labels: Bug Fix 🐛

#453 BUGZ-1248: Fix an error in the www content filter
  domainEntityFilters/www/README.md
  domainEntityFilters/www/filter.js
Labels: Bug Fix 🐛, Dev Approved, QA Approved

#451 Fix a bunch of Sit bugs and make it more stable
  usefulUtilities/sit/README.md
  usefulUtilities/sit/resources/animations/sittingIdle.fbx
  usefulUtilities/sit/resources/images/clickToSit.png
  usefulUtilities/sit/resources/images/holdToStandUp.png
  usefulUtilities/sit/resources/images/presit/pleaseFaceForward.png
  usefulUtilities/sit/resources/images/presit/sitConfirm1.png
  usefulUtilities/sit/resources/images/presit/sitConfirm10.png
  usefulUtilities/sit/resources/images/presit/sitConfirm11.png
  usefulUtilities/sit/resources/images/presit/sitConfirm12.png
  usefulUtilities/sit/resources/images/presit/sitConfirm2.png
  usefulUtilities/sit/resources/images/presit/sitConfirm3.png
  usefulUtilities/sit/resources/images/presit/sitConfirm4.png
  usefulUtilities/sit/resources/images/presit/sitConfirm5.png
  usefulUtilities/sit/resources/images/presit/sitConfirm6.png
  usefulUtilities/sit/resources/images/presit/sitConfirm7.png
  usefulUtilities/sit/resources/images/presit/sitConfirm8.png
  usefulUtilities/sit/resources/images/presit/sitConfirm9.png
  usefulUtilities/sit/resources/images/triggerToSit.png
  usefulUtilities/sit/resources/sittableUIClient.js
  usefulUtilities/sit/sitClient.js
  usefulUtilities/sit/sitServer.js
  usefulUtilities/sitV2/appResources/appData/resources/canSitZoneClient.js
  usefulUtilities/sitV2/appResources/appData/sitServerV2.js
Labels: Needs Code Review, QA Approved

#455 Whiteboard Jira 1298 Changing avatars causes paint sphere to be on wrong finger
  usefulUtilities/airAndWhiteboardDraw/README.md
  usefulUtilities/airAndWhiteboardDraw/entityResources/entityClientScripts/drawSphereClient.js
  usefulUtilities/airAndWhiteboardDraw/entityResources/entityClientScripts/drawSphereSpawnerClient.js
Labels: Bug Fix 🐛, Dev Approved, QA Approved

#456 Whiteboard DEV-433 Change texture file sizes
  usefulUtilities/airAndWhiteboardDraw/README.md
  usefulUtilities/airAndWhiteboardDraw/entityResources/resources/textures/black.png
  usefulUtilities/airAndWhiteboardDraw/entityResources/resources/textures/blue.png
  usefulUtilities/airAndWhiteboardDraw/entityResources/resources/textures/cyan.png
  usefulUtilities/airAndWhiteboardDraw/entityResources/resources/textures/green.png
  usefulUtilities/airAndWhiteboardDraw/entityResources/resources/textures/magenta.png
  usefulUtilities/airAndWhiteboardDraw/entityResources/resources/textures/neutral1.png
  usefulUtilities/airAndWhiteboardDraw/entityResources/resources/textures/neutral2.png
  usefulUtilities/airAndWhiteboardDraw/entityResources/resources/textures/neutral3.png
  usefulUtilities/airAndWhiteboardDraw/entityResources/resources/textures/neutral4.png
  usefulUtilities/airAndWhiteboardDraw/entityResources/resources/textures/red.png
  usefulUtilities/airAndWhiteboardDraw/entityResources/resources/textures/yellow.png
Labels: Dev Approved

#459 BUGZ-1386: Update simplifiedStatusIndicator to use domainID as org name instead of location.hostname
  usefulUtilities/statusIndicator/README.md
  usefulUtilities/statusIndicator/hifiScript/directoryClientScript/directoryClientScript.js
  usefulUtilities/statusIndicator/hifiScript/statusIndicator.js
Labels: Dev Approved
