Repository highfidelity/hifi-content, pull requests merged in 2019-07, with the labels that each got.

#431 [Dev-96] - New way to open Cal App
  usefulUtilities/hiFiCalendar/README.md
  usefulUtilities/hiFiCalendar/clientScripts/meetingRoomSetup_app.js
  usefulUtilities/hiFiCalendar/entities/calendarEntities.json
  usefulUtilities/hiFiCalendar/entities/tokenServer.json
  usefulUtilities/hiFiCalendar/entityScripts/clickForTheCalendarAppClientScript.js
  usefulUtilities/hiFiCalendar/entityScripts/showClickForTheCalendarAppClientScript.js
Labels: Dev Approved, QA Approved

#433 BUGZ-912 :: Calendar Grab Fix
  usefulUtilities/hiFiCalendar/README.md
  usefulUtilities/hiFiCalendar/entities/calendarEntities.json
Labels: Dev Approved, QA Approved

#432 BUGZ-922: Mirror is too dark in Interface after PR #15862
  usefulUtilities/mirror/README.md
  usefulUtilities/mirror/mirrorClient.js
Labels: Dev Approved, QA Approved

#434 New server-side sound emitter!
  usefulUtilities/soundEmitter/README.md
  usefulUtilities/soundEmitter/soundEmitterServer.js
Labels: Dev Approved, QA Ready

#438 [Bugz 537] :: Directory session display name fix
  usefulUtilities/statusIndicator/README.md
  usefulUtilities/statusIndicator/hifiScript/statusIndicator.js
Labels: Dev Approved

#437 DEV-258, DEV-260, DEV-261: Change overlays to local entities, set isVisibleInSecondaryCamera to false
  marketplaceItems/avatarCustomization101/README.md
  marketplaceItems/avatarCustomization101/appResources/appData/resources/modules/mirrorClient.js
  marketplaceItems/spectatorCamera/Description.txt
  marketplaceItems/spectatorCamera/spectatorCamera.js
  marketplaceItems/tabletCam/README.md
  marketplaceItems/tabletCam/appData/tabletCam_app.js
  marketplaceItems/tabletCam/marketplaceData/Marketplace Description.md
  usefulUtilities/mirror/README.md
  usefulUtilities/mirror/mirrorClient.js
Labels: Dev Approved, QA Approved

#441 Sound Emitter v1.2
  usefulUtilities/soundEmitter/README.md
  usefulUtilities/soundEmitter/soundEmitter.js
Labels: Dev Approved, QA Approved

#442 Fix mirrorReflection calling method names
  usefulUtilities/mirror/README.md
  usefulUtilities/mirror/mirrorReflection.js
Labels: Dev Approved, QA Approved

#443 DEV-302: Don't show the 'UNKNOWN TEAM' header when that's the only org name specified
  usefulUtilities/statusIndicator/README.md
  usefulUtilities/statusIndicator/webApp/www/js/formatStatusData.js
Labels: Dev Approved

#444 DEV-309: Remove the notion of 'Teams' from status indicator frontend and backend
  usefulUtilities/statusIndicator/README.md
  usefulUtilities/statusIndicator/webApp/app/statusIndicator_webApp.js
  usefulUtilities/statusIndicator/webApp/www/js/formatStatusData.js
  usefulUtilities/statusIndicator/webApp/www/teamPage.html
Labels: Dev Approved, QA Approved
