Repository highfidelity/hifi-content, pull requests merged in 2019-11, with the labels that each got.

#473 Screenshare
  usefulUtilities/hiFiCalendar/boardButtonClient.js
  usefulUtilities/smartBoard/.gitignore
  usefulUtilities/smartBoard/README.md
  usefulUtilities/smartBoard/html/screenshareClient.css
  usefulUtilities/smartBoard/html/screenshareClient.html
  usefulUtilities/smartBoard/html/screenshareClient.js
  usefulUtilities/smartBoard/resources/models/Smart-Board-v2-SS-FULL-MOCKUP.fbx
  usefulUtilities/smartBoard/resources/models/Smart-Board-v2-WB-FULL-MOCKUP.fbx
  usefulUtilities/smartBoard/resources/models/button-erase.fbx
  usefulUtilities/smartBoard/resources/models/button-start-screen-share.fbx
  usefulUtilities/smartBoard/resources/models/button-state-screen-share.fbx
  usefulUtilities/smartBoard/resources/models/button-state-whiteboard.fbx
  usefulUtilities/smartBoard/resources/models/button-stop-screen-share.fbx
  usefulUtilities/smartBoard/resources/models/screen-share-glass.fbx
  usefulUtilities/smartBoard/resources/models/smart-board-buttons-768-D.png
  usefulUtilities/smartBoard/resources/models/smart-board.fbx
  usefulUtilities/smartBoard/resources/models/sphere-white-emissive.fbx
  usefulUtilities/smartBoard/resources/models/whiteboard-button-container.fbx
  usefulUtilities/smartBoard/scripts/.gitignore
  usefulUtilities/smartBoard/scripts/boardButtonClient.js
  usefulUtilities/smartBoard/scripts/smartboardZoneClient.js
  usefulUtilities/smartBoard/scripts/smartboardZoneServer.js
  usefulUtilities/smartBoard/scripts/whiteboardMode/drawSphereClient.js
  usefulUtilities/smartBoard/scripts/whiteboardMode/drawSphereSpawnerClient.js
  usefulUtilities/smartBoard/scripts/whiteboardMode/resources/models/Smart-Board-v2-SS-FULL-MOCKUP.fbx
  usefulUtilities/smartBoard/scripts/whiteboardMode/resources/models/Smart-Board-v2-WB-FULL-MOCKUP.fbx
  usefulUtilities/smartBoard/scripts/whiteboardMode/resources/models/button-erase.fbx
  usefulUtilities/smartBoard/scripts/whiteboardMode/resources/models/button-start-screen-share.fbx
  usefulUtilities/smartBoard/scripts/whiteboardMode/resources/models/button-state-screen-share.fbx
  usefulUtilities/smartBoard/scripts/whiteboardMode/resources/models/button-state-whiteboard.fbx
  usefulUtilities/smartBoard/scripts/whiteboardMode/resources/models/button-stop-screen-share.fbx
  usefulUtilities/smartBoard/scripts/whiteboardMode/resources/models/screen-share-glass.fbx
  usefulUtilities/smartBoard/scripts/whiteboardMode/resources/models/smart-board.fbx
  usefulUtilities/smartBoard/scripts/whiteboardMode/resources/models/sphere-white-emissive.fbx
  usefulUtilities/smartBoard/scripts/whiteboardMode/resources/models/whiteboard-button-container.fbx
  usefulUtilities/smartBoard/scripts/whiteboardMode/resources/sounds/close.mp3
  usefulUtilities/smartBoard/scripts/whiteboardMode/resources/sounds/draw.mp3
  usefulUtilities/smartBoard/scripts/whiteboardMode/resources/sounds/open.mp3
  usefulUtilities/smartBoard/scripts/whiteboardMode/resources/sounds/resetSmartboard.mp3
  usefulUtilities/smartBoard/scripts/whiteboardMode/resources/textures/black.png
  usefulUtilities/smartBoard/scripts/whiteboardMode/resources/textures/blue.png
  usefulUtilities/smartBoard/scripts/whiteboardMode/resources/textures/cyan.png
  usefulUtilities/smartBoard/scripts/whiteboardMode/resources/textures/green.png
  usefulUtilities/smartBoard/scripts/whiteboardMode/resources/textures/magenta.png
  usefulUtilities/smartBoard/scripts/whiteboardMode/resources/textures/red.png
  usefulUtilities/smartBoard/scripts/whiteboardMode/resources/textures/yellow.png
  usefulUtilities/smartBoard/scripts/whiteboardMode/smartboardReset.js
Labels: Dev Approved

#475 Screenshare bugfixes
  usefulUtilities/smartBoard/README.md
  usefulUtilities/smartBoard/scripts/smartboardZoneClient.js
  usefulUtilities/smartBoard/scripts/smartboardZoneServer.js
Labels: Bug Fix 🐛, Dev Approved

#476 updated localButton visible behavior
  usefulUtilities/smartBoard/README.md
  usefulUtilities/smartBoard/html/screenshareClient.css
  usefulUtilities/smartBoard/scripts/smartboardZoneClient.js
  usefulUtilities/smartBoard/scripts/smartboardZoneServer.js
  usefulUtilities/smartBoard/scripts/whiteboardMode/drawSphereClient.js
  usefulUtilities/smartBoard/scripts/whiteboardMode/drawSphereSpawnerClient.js
Labels: Needs Code Review

#477 dev-2795/fix-multiple-color-sphere-pops
  usefulUtilities/smartBoard/README.md
  usefulUtilities/smartBoard/scripts/boardButtonClient.js
Labels: Needs Code Review

#478 Smartboard v1.3: Attempt to fix DEV-2821 and DEV-2815
  usefulUtilities/smartBoard/README.md
  usefulUtilities/smartBoard/scripts/boardButtonClient.js
  usefulUtilities/smartBoard/scripts/smartboardZoneClient.js
  usefulUtilities/smartBoard/scripts/smartboardZoneServer.js
Labels: Bug Fix 🐛, Dev Approved, QA Ready

#479 DEV-2840: Fix z-fighting issues in Smartboard and enable quicker positional iteration in the future
  usefulUtilities/smartBoard/README.md
  usefulUtilities/smartBoard/scripts/smartboardZoneClient.js
  usefulUtilities/smartBoard/scripts/whiteboardMode/drawSphereClient.js
Labels: Bug Fix 🐛, Needs Code Review
