Repository highfidelity/hifi-content, pull requests merged in 2019-09, with the labels that each got.

#458 Make Sit more robust: Fix double sit overlays, fix invisible sit overlays (hopefully)
  usefulUtilities/sit/README.md
  usefulUtilities/sit/sitClient.js
  usefulUtilities/sit/sitServer.js
Labels: Bug Fix 🐛, Dev Approved, QA Approved

#461 Chatterboxes with privacy mode!
  placeSpecificContent/hq/chatterboxes/README.md
  placeSpecificContent/hq/chatterboxes/chatterbox/buttons/privacyButton_client.js
  placeSpecificContent/hq/chatterboxes/chatterbox/buttons/privacyButton_server.js
  placeSpecificContent/hq/chatterboxes/resources/sounds/DONE_SOUND.mp3
  placeSpecificContent/hq/chatterboxes/resources/sounds/TRANSITION_SOUND.mp3
Labels: Dev Approved, QA Approved

#464 Empty script
  modules/empty/README.md
  modules/empty/empty.js
Labels: Dev Approved

#462 Configurable courtyard
  placeSpecificContent/hq/courtyard/README.md
  placeSpecificContent/hq/courtyard/controlPanel/buttons/controlPanelButton_client.js
  placeSpecificContent/hq/courtyard/controlPanel/controlPanel_server.js
  placeSpecificContent/hq/courtyard/controlPanel/resources/sounds/DONE_SOUND.mp3
  placeSpecificContent/hq/courtyard/controlPanel/resources/sounds/TRANSITION_SOUND.mp3
Labels: Needs Code Review, QA Approved

#465 DEV-546: Make Click to Sit overlay more opaque
  usefulUtilities/sit/README.md
  usefulUtilities/sit/resources/sittableUIClient.js
  usefulUtilities/sit/sitClient.js
Labels: Dev Approved

#460 BUGZ-1368: When using relative path destinations, portals should send a users' feet to the destination
  usefulUtilities/portal/README.md
  usefulUtilities/portal/portal.js
Labels: Dev Approved, QA Approved

#463 Bouncer Zone
  usefulUtilities/bouncerZone/README.md
  usefulUtilities/bouncerZone/bouncerZone.js
  usefulUtilities/bouncerZone/resources/sounds/ZAP.mp3
Labels: Dev Approved, QA Approved

#466 DEV-633: Allow users of the Deploy Tool to modify entities' userData
  usefulUtilities/deployNewScripts/README.md
  usefulUtilities/deployNewScripts/deployNewScripts_app.js
  usefulUtilities/deployNewScripts/ui/css/deployNewScripts_ui.css
  usefulUtilities/deployNewScripts/ui/deployNewScripts_ui.html
  usefulUtilities/deployNewScripts/ui/js/deployNewScripts_ui.js
Labels: Dev Approved
