Repository highfidelity/hifi-content, pull requests merged in 2019-03, with the labels that each got.

#294 Transition Bingo backend to Experiences backend
  .eslintrc.js
  events/bingo/.gitignore
  events/bingo/README.md
  events/bingo/architectureSlides/1.png
  events/bingo/architectureSlides/2.png
  events/bingo/architectureSlides/3.png
  events/bingo/architectureSlides/4.png
  events/bingo/architectureSlides/5.png
  events/bingo/architectureSlides/6.png
  events/bingo/architectureSlides/7.png
  events/bingo/architectureSlides/8.png
  events/bingo/bingoBossApp/bingoBossApp_app.js
  events/bingo/bingoBossApp/bingoBossApp_ui.css
  events/bingo/bingoBossApp/bingoBossApp_ui.html
  events/bingo/bingoBossApp/ui/bingoBossApp_ui.html
  events/bingo/bingoBossApp/ui/css/bingoBossApp_ui.css
  events/bingo/bingoBossApp/ui/js/bingoBossApp_ui.js
  events/bingo/bingoCardApp/bingoCard_app.js
  events/bingo/bingoCardApp/bingoCard_ui.html
  events/bingo/bingoCardApp/ui/bingoCard_ui.html
  events/bingo/bingoCardApp/ui/css/bingoCard_ui.css
  events/bingo/bingoCardApp/ui/images/bingo-card-head.png
  events/bingo/bingoCardApp/ui/js/bingoCard_ui.js
  events/bingo/entityScripts/bingoWheel/bingoWheel.js
  events/bingo/entityScripts/bingoWheel/sounds/blip.wav
  events/bingo/entityScripts/cardRemover/bingoCardRemover.js
  events/bingo/entityScripts/cardSpawner/bingoCardSpawner.js
  events/bingo/entityScripts/scannerEntryZone/bingoScannerEntryZone.js
  events/bingo/entityScripts/scannerZone/bingoScannerZone.js
  events/bingo/serverScripts/bingoPlayerCounter/bingoPlayerCounterServer.js
  events/bingo/serverScripts/bingoScannerZone/bingoScannerParticleServer.js
  events/bingo/serverScripts/bingoScannerZone/bingoScannerZoneServer.js
  events/bingo/serverScripts/bingoWheel/bingoWheelServer.js
  events/bingo/serverScripts/bingoWheel/sounds/blip.wav
  events/bingo/serverScripts/bingoWheel/sounds/wheelSpin.mp3
  events/bingo/serverScripts/gates/gateServer.js
  events/bingo/serverScripts/scannerEntryZone/bingoScannerEntryZoneServer.js
  events/bingo/testApp/assets/icons/bingotest-a.svg
  events/bingo/testApp/assets/icons/bingotest-i.svg
  events/bingo/testApp/bingoTestApp_app.js
  events/bingo/testApp/ui/bingoTestApp_ui.html
  events/bingo/testApp/ui/css/style.css
  events/bingo/testApp/ui/images/loadingSpinner.svg
  events/bingo/testApp/ui/js/bingoTestApp_ui.js
  events/bingo/webApps/bingo.js
  events/bingo/webApps/package-lock.json
  events/bingo/webApps/package.json
Labels: Dev Approved, Experiences, QA Approved

#302 Optimize Appreciate app; handle Z keypress on DOM
  marketplaceItems/appreciate/README.md
  marketplaceItems/appreciate/appResources/appData/appreciate_app.js
  marketplaceItems/appreciate/appResources/appData/resources/appreciate_ui.html
  marketplaceItems/appreciate/appResources/appData/resources/css/style.css
  marketplaceItems/appreciate/appResources/appData/resources/js/appreciate_ui.js
  marketplaceItems/appreciate/marketplaceResources/description.md
Labels: Dev Approved, Experiences, QA Approved

#312 Appreciate App: Small fixes
  marketplaceItems/appreciate/README.md
  marketplaceItems/appreciate/appResources/appData/appreciate_app.js
  marketplaceItems/appreciate/appResources/appData/resources/appreciate_ui.html
  marketplaceItems/appreciate/marketplaceResources/description.md
Labels: Bug Fix 🐛, Experiences, Needs Code Review, QA Ready (internal)

#314 Bingo Boss App: Add a confirmation popup for buttons that start a new round
  events/bingo/README.md
  events/bingo/bingoBossApp/ui/bingoBossApp_ui.html
  events/bingo/bingoBossApp/ui/css/bingoBossApp_ui.css
  events/bingo/bingoBossApp/ui/js/bingoBossApp_ui.js
Labels: Experiences, Needs Code Review, QA Ready (internal)

#319 Multi-Con Vote App
  events/multiCon/.gitignore
  events/multiCon/README.md
  events/multiCon/config/config.json
  events/multiCon/multiConApp/assets/icons/vote-a.svg
  events/multiCon/multiConApp/assets/icons/vote-i.svg
  events/multiCon/multiConApp/multiConApp_app.js
  events/multiCon/multiConApp/ui/css/multiConApp_ui.css
  events/multiCon/multiConApp/ui/images/check.svg
  events/multiCon/multiConApp/ui/images/close.svg
  events/multiCon/multiConApp/ui/images/close_inverted.svg
  events/multiCon/multiConApp/ui/images/header.jpg
  events/multiCon/multiConApp/ui/images/loadingSpinner.svg
  events/multiCon/multiConApp/ui/images/schedule.jpg
  events/multiCon/multiConApp/ui/js/multiConApp_ui.js
  events/multiCon/multiConApp/ui/multiConApp_ui.html
  events/multiCon/webApps/multiConVote/multiConVote.js
  events/multiCon/webApps/multiConVote/package-lock.json
  events/multiCon/webApps/multiConVote/package.json
Labels: Dev Approved, Experiences, QA Approved

#323 "Become Avatar" usefulUtility and JAT's script
  events/multiCon/jamesArnoldTaylor/.gitignore
  events/multiCon/jamesArnoldTaylor/JATScript.js
  events/multiCon/jamesArnoldTaylor/README.md
  events/multiCon/jamesArnoldTaylor/models/playback_ff-rw-button.fbx
  events/multiCon/jamesArnoldTaylor/models/playback_pause-button.fbx
  events/multiCon/jamesArnoldTaylor/models/playback_play-button.fbx
  usefulUtilities/becomeAvatar/README.md
  usefulUtilities/becomeAvatar/becomeAvatar.js
Labels: Dev Approved, QA Approved

#324 Bingo v3.0
  events/bingo/README.md
  events/bingo/bingoWinnerApp/assets/icons/bingo-a.svg
  events/bingo/bingoWinnerApp/assets/icons/bingo-i.svg
  events/bingo/bingoWinnerApp/bingoWinner_app.js
  events/bingo/bingoWinnerApp/ui/bingoWinner_ui.html
  events/bingo/bingoWinnerApp/ui/css/bingoWinner_ui.css
  events/bingo/bingoWinnerApp/ui/images/loadingSpinner.svg
  events/bingo/bingoWinnerApp/ui/js/bingoWinner_ui.js
  events/bingo/entityScripts/bingoBouncerZone/bouncerZone.js
  events/bingo/entityScripts/bingoPrizeDoorZone/bingoPrizeDoorZone.js
  events/bingo/serverScripts/bingoWheel/bingoWheelServer.js
  events/bingo/webApps/bingo.js
Labels: Dev Approved, QA Approved

#313 Nametag
  .eslintrc.js
  marketplaceItems/nameTag/README.md
  marketplaceItems/nameTag/appResources/appData/resources/modules/defaultLocalEntityProps.js
  marketplaceItems/userInspector/README.md
  marketplaceItems/userInspector/appResources/appData/resources/css/style.css
  marketplaceItems/userInspector/appResources/appData/resources/images/icons/inspector-a.svg
  marketplaceItems/userInspector/appResources/appData/resources/images/icons/inspector-i.svg
  marketplaceItems/userInspector/appResources/appData/resources/images/loadingSpinner.svg
  marketplaceItems/userInspector/appResources/appData/resources/js/userInspector_ui.js
  marketplaceItems/userInspector/appResources/appData/resources/modules/defaultLocalEntityProps.js
  marketplaceItems/userInspector/appResources/appData/resources/modules/entityMaker.js
  marketplaceItems/userInspector/appResources/appData/resources/modules/nameTagListManager.js
  marketplaceItems/userInspector/appResources/appData/resources/modules/objectAssign.js
  marketplaceItems/userInspector/appResources/appData/resources/modules/pickRayController.js
  marketplaceItems/userInspector/appResources/appData/resources/modules/textHelper.js
  marketplaceItems/userInspector/appResources/appData/resources/userInspector_ui.html
  marketplaceItems/userInspector/appResources/appData/userInspector.js
  marketplaceItems/userInspector/appResources/userInspector.app.json
  marketplaceItems/userInspector/marketplaceResources/Description.md
  marketplaceItems/userInspector/marketplaceResources/userInspector.jpg
Labels: Dev Approved, QA Approved

#326 Three new usefulUtilities
  events/multiCon/config/.gitignore
  usefulUtilities/avatarEntityRemover/README.md
  usefulUtilities/avatarEntityRemover/avatarEntityRemover.js
  usefulUtilities/lockedAvatarEntityRemover/README.md
  usefulUtilities/lockedAvatarEntityRemover/lockedAvatarEntityRemover.js
  usefulUtilities/pushPreventer/README.md
  usefulUtilities/pushPreventer/pushPreventer.js
Labels: Dev Approved, QA Approved

#325 Slight improvements to the Bingo webapp
  events/bingo/README.md
  events/bingo/webApps/bingo.js
Labels: Dev Approved, QA Approved

#328 "Toggle Fly Button" fix
  usefulUtilities/toggleFlyButton/README.md
  usefulUtilities/toggleFlyButton/toggleFlyButton.js
Labels: Dev Approved, QA Approved

#327 "Deploy New Scripts" app!
  usefulUtilities/deployNewScripts/README.md
  usefulUtilities/deployNewScripts/assets/icons/deploy-a.svg
  usefulUtilities/deployNewScripts/assets/icons/deploy-i.svg
  usefulUtilities/deployNewScripts/deployNewScripts_app.js
  usefulUtilities/deployNewScripts/ui/css/deployNewScripts_ui.css
  usefulUtilities/deployNewScripts/ui/deployNewScripts_ui.html
  usefulUtilities/deployNewScripts/ui/images/loadingSpinner.svg
  usefulUtilities/deployNewScripts/ui/js/deployNewScripts_ui.js
Labels: Dev Approved, QA Approved

#320 Model json clean up
  usefulUtilities/modelJSONCleanup/README.md
  usefulUtilities/modelJSONCleanup/config.json
  usefulUtilities/modelJSONCleanup/modelJSONCleanup.js
  usefulUtilities/modelJSONCleanup/theSpot/config.json
Labels: Dev Approved, QA Approved

#335 Update loud app
  usefulUtilities/loudApp/README.md
  usefulUtilities/loudApp/appResources/loudApp_app.js
  usefulUtilities/loudApp/appResources/resources/css/app.css
  usefulUtilities/loudApp/appResources/resources/icons/seek loud-a.svg
  usefulUtilities/loudApp/appResources/resources/icons/seek loud-i.svg
  usefulUtilities/loudApp/appResources/resources/js/loudApp_ui.js
  usefulUtilities/loudApp/appResources/resources/loudApp_ui.html
Labels: QA Approved

#334 Fix Legacy support.js Chat App
  DomainContent/Start/html/ChatPage.html
  DomainContent/Start/support.js
Labels: Dev Approved, QA Approved

#336 Allow multiple Bingo prize doors to contain the same prize
  events/bingo/README.md
  events/bingo/serverScripts/bingoWheel/bingoWheelServer.js
Labels: Needs Code Review, QA Approved
