Repository highfidelity/hifi-content, pull requests merged in 2019-02, with the labels that each got.

#274 Added users to spin wheel and bouncer zones, remove extra var, and fix one broken file path
  events/bingo/README.md
  events/bingo/entityScripts/bingoBouncerZone/bouncerZone.js
  events/bingo/entityScripts/bingoWheel/bingoWheel.js
  events/bingo/entityScripts/cardSpawner/bingoCardSpawner.js
  events/bingo/serverScripts/bingoWheel/bingoWheelServer.js
Labels: Experiences, Work In-Progress

#272 Fixed velocity properties on attached items
  DomainContent/AvatarStore/attachmentItemScript.js
Labels: Bug Fix 🐛, Experiences, Needs Code Review

#277 Updated prize name for oculus
  events/bingo/serverScripts/bingoWheel/bingoWheelServer.js
Labels: Bug Fix 🐛, Experiences, Needs Code Review

#295 App Loader script
  usefulUtilities/appLoader/README.md
  usefulUtilities/appLoader/appLoader.js
Labels: Dev Approved, Experiences, QA Approved

#292 Appreciation App
  marketplaceItems/appreciate/README.md
  marketplaceItems/appreciate/appResources/appData/appreciate_app.js
  marketplaceItems/appreciate/appResources/appData/resources/animations/Cheering.fbx
  marketplaceItems/appreciate/appResources/appData/resources/animations/Clapping.fbx
  marketplaceItems/appreciate/appResources/appData/resources/appreciate_ui.html
  marketplaceItems/appreciate/appResources/appData/resources/css/style.css
  marketplaceItems/appreciate/appResources/appData/resources/images/icons/appreciate-a.svg
  marketplaceItems/appreciate/appResources/appData/resources/images/icons/appreciate-i.svg
  marketplaceItems/appreciate/appResources/appData/resources/images/loadingSpinner.svg
  marketplaceItems/appreciate/appResources/appData/resources/js/appreciate_ui.js
  marketplaceItems/appreciate/appResources/appData/resources/js/jscolor.js
  marketplaceItems/appreciate/appResources/appData/resources/sounds/claps/01.wav
  marketplaceItems/appreciate/appResources/appData/resources/sounds/claps/02.wav
  marketplaceItems/appreciate/appResources/appData/resources/sounds/claps/03.wav
  marketplaceItems/appreciate/appResources/appData/resources/sounds/claps/04.wav
  marketplaceItems/appreciate/appResources/appData/resources/sounds/claps/05.wav
  marketplaceItems/appreciate/appResources/appData/resources/sounds/claps/06.wav
  marketplaceItems/appreciate/appResources/appData/resources/sounds/claps/07.wav
  marketplaceItems/appreciate/appResources/appData/resources/sounds/claps/08.wav
  marketplaceItems/appreciate/appResources/appData/resources/sounds/claps/09.wav
  marketplaceItems/appreciate/appResources/appData/resources/sounds/claps/10.wav
  marketplaceItems/appreciate/appResources/appData/resources/sounds/claps/11.wav
  marketplaceItems/appreciate/appResources/appData/resources/sounds/claps/12.wav
  marketplaceItems/appreciate/appResources/appData/resources/sounds/claps/13.wav
  marketplaceItems/appreciate/appResources/appData/resources/sounds/claps/14.wav
  marketplaceItems/appreciate/appResources/appData/resources/sounds/claps/15.wav
  marketplaceItems/appreciate/appResources/appData/resources/sounds/claps/16.wav
  marketplaceItems/appreciate/appResources/appData/resources/sounds/whistles/01.wav
  marketplaceItems/appreciate/appResources/appData/resources/sounds/whistles/02.wav
  marketplaceItems/appreciate/appResources/appData/resources/sounds/whistles/03.wav
  marketplaceItems/appreciate/appResources/appData/resources/sounds/whistles/04.wav
  marketplaceItems/appreciate/appResources/appData/resources/sounds/whistles/05.wav
  marketplaceItems/appreciate/appResources/appData/resources/sounds/whistles/06.wav
  marketplaceItems/appreciate/appResources/appData/resources/sounds/whistles/07.wav
  marketplaceItems/appreciate/appResources/appData/resources/sounds/whistles/08.wav
  marketplaceItems/appreciate/appResources/appData/resources/sounds/whistles/09.wav
  marketplaceItems/appreciate/appResources/appData/resources/sounds/whistles/10.wav
  marketplaceItems/appreciate/appResources/appData/resources/sounds/whistles/11.wav
  marketplaceItems/appreciate/appResources/appData/resources/sounds/whistles/12.wav
  marketplaceItems/appreciate/appResources/appData/resources/sounds/whistles/13.wav
  marketplaceItems/appreciate/appResources/appData/resources/sounds/whistles/14.wav
  marketplaceItems/appreciate/appResources/appData/resources/sounds/whistles/15.wav
  marketplaceItems/appreciate/appResources/appData/resources/sounds/whistles/16.wav
  marketplaceItems/appreciate/appResources/appData/resources/sounds/whistles/17.wav
  marketplaceItems/appreciate/appResources/appreciate.app.json
  marketplaceItems/appreciate/marketplaceResources/appreciate.jpg
  marketplaceItems/appreciate/marketplaceResources/description.md
Labels: Dev Approved, Experiences, QA Approved

#297 Cleanup old IntensityEntities on startup/shutdown
  marketplaceItems/appreciate/README.md
  marketplaceItems/appreciate/appResources/appData/appreciate_app.js
  marketplaceItems/appreciate/marketplaceResources/description.md
Labels: Experiences, Needs Code Review, QA Approved

#298 Appreciate: Introduce functionality to stop running baked versions
  marketplaceItems/appreciate/README.md
  marketplaceItems/appreciate/appResources/appData/appreciate_app.js
  marketplaceItems/appreciate/marketplaceResources/description.md
Labels: Dev Approved, Experiences, QA Approved

#291 Draw app
  marketplaceItems/draw/README.md
  marketplaceItems/draw/appResources/appData/draw_app.js
  marketplaceItems/draw/appResources/appData/resources/css/draw_ui.css
  marketplaceItems/draw/appResources/appData/resources/draw_ui.html
  marketplaceItems/draw/appResources/appData/resources/icons/draw-a.png
  marketplaceItems/draw/appResources/appData/resources/icons/draw-i.png
  marketplaceItems/draw/appResources/appData/resources/models/sphere-white-emissive.fbx
  marketplaceItems/draw/appResources/appData/resources/sounds/close.mp3
  marketplaceItems/draw/appResources/appData/resources/sounds/draw.mp3
  marketplaceItems/draw/appResources/appData/resources/sounds/open.mp3
  marketplaceItems/draw/appResources/appData/resources/textures/black.png
  marketplaceItems/draw/appResources/appData/resources/textures/blue.png
  marketplaceItems/draw/appResources/appData/resources/textures/cyan.png
  marketplaceItems/draw/appResources/appData/resources/textures/green.png
  marketplaceItems/draw/appResources/appData/resources/textures/magenta.png
  marketplaceItems/draw/appResources/appData/resources/textures/neutral1.png
  marketplaceItems/draw/appResources/appData/resources/textures/neutral2.png
  marketplaceItems/draw/appResources/appData/resources/textures/neutral3.png
  marketplaceItems/draw/appResources/appData/resources/textures/neutral4.png
  marketplaceItems/draw/appResources/appData/resources/textures/red.png
  marketplaceItems/draw/appResources/draw.app.json
  marketplaceItems/draw/draw_app.js
  marketplaceItems/draw/marketplaceResources/description.md
  marketplaceItems/draw/marketplaceResources/draw.jpg
Labels: Dev Approved, Experiences, QA Approved

#304 Add a 'Marketplace Item Advertiser' to 'usefulUtilities'
  usefulUtilities/marketplaceItemAdvertiser/README.md
  usefulUtilities/marketplaceItemAdvertiser/marketplaceItemAdvertiser.js
Labels: Experiences, Needs Code Review, QA Approved

#307 Implement a Script Pauser entity script
  usefulUtilities/scriptPauser/README.md
  usefulUtilities/scriptPauser/scriptPauser.js
Labels: Experiences, Needs Code Review, QA Ready (internal)

#308 Final Question App version for testing at Town Hall
  marketplaceItems/questionApp/README.md
  marketplaceItems/questionApp/appResources/appData/question_app.js
  marketplaceItems/questionApp/appResources/appData/resources/css/question_ui.css
  marketplaceItems/questionApp/appResources/appData/resources/icons/question-a.png
  marketplaceItems/questionApp/appResources/appData/resources/icons/question-i.png
  marketplaceItems/questionApp/appResources/appData/resources/images/voxel.png
  marketplaceItems/questionApp/appResources/appData/resources/models/questionMark.fbx
  marketplaceItems/questionApp/appResources/appData/resources/modules/pickRayController.js
  marketplaceItems/questionApp/appResources/appData/resources/question_ui.html
  marketplaceItems/questionApp/appResources/appData/resources/sounds/close.mp3
  marketplaceItems/questionApp/appResources/appData/resources/sounds/open.mp3
  marketplaceItems/questionApp/appResources/appData/resources/sounds/selected.mp3
  marketplaceItems/questionApp/appResources/question.app.json
  marketplaceItems/questionApp/marketplaceResources/description.md
  marketplaceItems/questionApp/marketplaceResources/question.jpg
Labels: Experiences, Needs Code Review, QA in-progress (internal)
