Repository highfidelity/hifi-content, pull requests merged in 2019-01, with the labels that each got.

#243 Eslint fix
  .eslintrc.js
Labels: Dev Approved

#235 Update painting with new link
  Marketplace/primitive-painting/Primitive_Painting_Set.json
Labels: Dev Approved

#242 Added Fix for grabbing textures
  Prototyping/HappyKiosk/Happy-Kiosk_Button_Server.js
Labels: QA Approved

#216 Kayla Camera Update
  Prototyping/Kayla-Camera/Kayla-Camera.js
  Prototyping/Kayla-Camera/Tablet/Kayla-Camera-Tablet.html
  Prototyping/Kayla-Camera/Tablet/js/Kayla-Camera-Tablet.js
Labels: Experiences, Feedback in-progress

#244 Keyboard
  marketplaceItems/keyboardBlueprint/README.md
  marketplaceItems/keyboardBlueprint/entity/keyboard.json
  marketplaceItems/keyboardBlueprint/entityClientScripts/keyboardKey.js
  marketplaceItems/keyboardBlueprint/entityClientScripts/keyboardZone.js
  marketplaceItems/keyboardBlueprint/marketplaceResources/description.md
  marketplaceItems/keyboardBlueprint/resources/images/Keyboard.jpg
  marketplaceItems/keyboardBlueprint/resources/sounds/1.wav
  marketplaceItems/keyboardBlueprint/resources/sounds/10.wav
  marketplaceItems/keyboardBlueprint/resources/sounds/11.wav
  marketplaceItems/keyboardBlueprint/resources/sounds/12.wav
  marketplaceItems/keyboardBlueprint/resources/sounds/13.wav
  marketplaceItems/keyboardBlueprint/resources/sounds/14.wav
  marketplaceItems/keyboardBlueprint/resources/sounds/15.wav
  marketplaceItems/keyboardBlueprint/resources/sounds/16.wav
  marketplaceItems/keyboardBlueprint/resources/sounds/17.wav
  marketplaceItems/keyboardBlueprint/resources/sounds/18.wav
  marketplaceItems/keyboardBlueprint/resources/sounds/19.wav
  marketplaceItems/keyboardBlueprint/resources/sounds/2.wav
  marketplaceItems/keyboardBlueprint/resources/sounds/20.wav
  marketplaceItems/keyboardBlueprint/resources/sounds/21.wav
  marketplaceItems/keyboardBlueprint/resources/sounds/22.wav
  marketplaceItems/keyboardBlueprint/resources/sounds/23.wav
  marketplaceItems/keyboardBlueprint/resources/sounds/24.wav
  marketplaceItems/keyboardBlueprint/resources/sounds/25.wav
  marketplaceItems/keyboardBlueprint/resources/sounds/26.wav
  marketplaceItems/keyboardBlueprint/resources/sounds/27.wav
  marketplaceItems/keyboardBlueprint/resources/sounds/28.wav
  marketplaceItems/keyboardBlueprint/resources/sounds/29.wav
  marketplaceItems/keyboardBlueprint/resources/sounds/3.wav
  marketplaceItems/keyboardBlueprint/resources/sounds/30.wav
  marketplaceItems/keyboardBlueprint/resources/sounds/31.wav
  marketplaceItems/keyboardBlueprint/resources/sounds/32.wav
  marketplaceItems/keyboardBlueprint/resources/sounds/33.wav
  marketplaceItems/keyboardBlueprint/resources/sounds/34.wav
  marketplaceItems/keyboardBlueprint/resources/sounds/35.wav
  marketplaceItems/keyboardBlueprint/resources/sounds/36.wav
  marketplaceItems/keyboardBlueprint/resources/sounds/37.wav
  marketplaceItems/keyboardBlueprint/resources/sounds/38.wav
  marketplaceItems/keyboardBlueprint/resources/sounds/39.wav
  marketplaceItems/keyboardBlueprint/resources/sounds/4.wav
  marketplaceItems/keyboardBlueprint/resources/sounds/40.wav
  marketplaceItems/keyboardBlueprint/resources/sounds/41.wav
  marketplaceItems/keyboardBlueprint/resources/sounds/42.wav
  marketplaceItems/keyboardBlueprint/resources/sounds/43.wav
  marketplaceItems/keyboardBlueprint/resources/sounds/44.wav
  marketplaceItems/keyboardBlueprint/resources/sounds/45.wav
  marketplaceItems/keyboardBlueprint/resources/sounds/46.wav
  marketplaceItems/keyboardBlueprint/resources/sounds/47.wav
  marketplaceItems/keyboardBlueprint/resources/sounds/48.wav
  marketplaceItems/keyboardBlueprint/resources/sounds/49.wav
  marketplaceItems/keyboardBlueprint/resources/sounds/5.wav
  marketplaceItems/keyboardBlueprint/resources/sounds/6.wav
  marketplaceItems/keyboardBlueprint/resources/sounds/7.wav
  marketplaceItems/keyboardBlueprint/resources/sounds/8.wav
  marketplaceItems/keyboardBlueprint/resources/sounds/9.wav
Labels: Dev Approved, Experiences, QA Approved

#252 Fixed audio file path and added MP Key image
  marketplaceItems/keyboardBlueprint/entityClientScripts/keyboardKey.js
  marketplaceItems/keyboardBlueprint/marketplaceResources/Blueprint-Keyboard.png
Labels: Experiences, Needs Code Review

#254 Mirror Update: Cap long-side resolution of mirror to 960px
  usefulUtilities/mirror/README.md
  usefulUtilities/mirror/mirrorClient.js
  usefulUtilities/mirror/mirrorReflection.js
Labels: Experiences, Needs Code Review, QA Approved

#251 Solo point
  marketplaceItems/audioFocus/README.md
  marketplaceItems/audioFocus/appResources/appData/audioFocus_app.js
  marketplaceItems/audioFocus/appResources/appData/resources/audioFocus_ui.html
  marketplaceItems/audioFocus/appResources/appData/resources/css/style.css
  marketplaceItems/audioFocus/appResources/appData/resources/images/focus.png
  marketplaceItems/audioFocus/appResources/appData/resources/images/icons/focus-a.svg
  marketplaceItems/audioFocus/appResources/appData/resources/images/icons/focus-i.svg
  marketplaceItems/audioFocus/appResources/appData/resources/images/speaker.png
  marketplaceItems/audioFocus/appResources/appData/resources/js/audioFocus_ui.js
  marketplaceItems/audioFocus/appResources/audioFocus.app.json
  marketplaceItems/audioFocus/marketplaceResources/Description.md
  marketplaceItems/audioFocus/marketplaceResources/keyImage.png
Labels: Feedback welcome

#258 Toggle Fly Button
  usefulUtilities/toggleFlyButton/README.md
  usefulUtilities/toggleFlyButton/toggleFlyButton.js
Labels: Dev Approved, QA Approved

#248 Vote app
  .gitignore
  usefulUtilities/voteApp/.gitignore
  usefulUtilities/voteApp/README.md
  usefulUtilities/voteApp/appResources/resources/config.js
  usefulUtilities/voteApp/appResources/resources/css/app.css
  usefulUtilities/voteApp/appResources/resources/css/glyphs/fonts/hifi-glyphs.eot
  usefulUtilities/voteApp/appResources/resources/css/glyphs/fonts/hifi-glyphs.svg
  usefulUtilities/voteApp/appResources/resources/css/glyphs/fonts/hifi-glyphs.ttf
  usefulUtilities/voteApp/appResources/resources/css/glyphs/fonts/hifi-glyphs.woff
  usefulUtilities/voteApp/appResources/resources/css/glyphs/icons-reference.html
  usefulUtilities/voteApp/appResources/resources/css/glyphs/styles.css
  usefulUtilities/voteApp/appResources/resources/css/icons/go-button.png
  usefulUtilities/voteApp/appResources/resources/css/icons/gobutton.svg
  usefulUtilities/voteApp/appResources/resources/css/icons/spinner.gif
  usefulUtilities/voteApp/appResources/resources/css/modal/modal.css
  usefulUtilities/voteApp/appResources/resources/icons/vote-a.svg
  usefulUtilities/voteApp/appResources/resources/icons/vote-i.svg
  usefulUtilities/voteApp/appResources/resources/images/tree-voting-feature-img.jpg
  usefulUtilities/voteApp/appResources/resources/js/voteApp_ui.js
  usefulUtilities/voteApp/appResources/resources/voteApp_ui.html
  usefulUtilities/voteApp/appResources/voteApp.js
Labels: Needs Code Review, QA Approved

#256 Sit script update to see invisible cubes in create mode
  Prototyping/Sit/sit.js
  marketplaceItems/sitPoint/README.md
  marketplaceItems/sitPoint/appResources/appData/resources/animations/sittingIdle.fbx
  marketplaceItems/sitPoint/appResources/appData/resources/images/clickToSit.png
  marketplaceItems/sitPoint/appResources/appData/resources/images/holdToStandUp.png
  marketplaceItems/sitPoint/appResources/appData/resources/images/presit/pleaseFaceForward.png
  marketplaceItems/sitPoint/appResources/appData/resources/images/presit/sitConfirm1.png
  marketplaceItems/sitPoint/appResources/appData/resources/images/presit/sitConfirm10.png
  marketplaceItems/sitPoint/appResources/appData/resources/images/presit/sitConfirm11.png
  marketplaceItems/sitPoint/appResources/appData/resources/images/presit/sitConfirm12.png
  marketplaceItems/sitPoint/appResources/appData/resources/images/presit/sitConfirm2.png
  marketplaceItems/sitPoint/appResources/appData/resources/images/presit/sitConfirm3.png
  marketplaceItems/sitPoint/appResources/appData/resources/images/presit/sitConfirm4.png
  marketplaceItems/sitPoint/appResources/appData/resources/images/presit/sitConfirm5.png
  marketplaceItems/sitPoint/appResources/appData/resources/images/presit/sitConfirm6.png
  marketplaceItems/sitPoint/appResources/appData/resources/images/presit/sitConfirm7.png
  marketplaceItems/sitPoint/appResources/appData/resources/images/presit/sitConfirm8.png
  marketplaceItems/sitPoint/appResources/appData/resources/images/presit/sitConfirm9.png
  marketplaceItems/sitPoint/appResources/appData/resources/images/triggerToSit.png
  marketplaceItems/sitPoint/appResources/appData/sitClient.js
  marketplaceItems/sitPoint/appResources/appData/sitServer.js
  marketplaceItems/sitPoint/appResources/json/invisibleSitCube.json
  marketplaceItems/sitPoint/appResources/json/opaqueSitCube.json
  marketplaceItems/sitPoint/marketplaceResources/description.md
  marketplaceItems/sitPoint/marketplaceResources/keyImage.jpg
Labels: Needs Code Review, QA Approved

#260 Move digital picture frame to marketplaceItems from Marketplace directory
  Marketplace/photoFrame/images/keyImage.PNG
  Marketplace/photoFrame/images/userdata.PNG
  marketplaceItems/digitalPictureFrame/README.md
  marketplaceItems/digitalPictureFrame/entities/digitalPictureFrame.json
  marketplaceItems/digitalPictureFrame/entityServerScripts/digitalFrame.js
  marketplaceItems/digitalPictureFrame/marketplaceResources/Blueprint-Digital-Picture-Frame.jpg
  marketplaceItems/digitalPictureFrame/marketplaceResources/description.md
  marketplaceItems/digitalPictureFrame/resources/default-image-model.fbx
  marketplaceItems/digitalPictureFrame/resources/image1.jpg
  marketplaceItems/digitalPictureFrame/resources/image2.jpg
  marketplaceItems/digitalPictureFrame/resources/image3.jpg
  marketplaceItems/digitalPictureFrame/resources/image4.jpg
  marketplaceItems/digitalPictureFrame/resources/image5.jpg
Labels: Needs Code Review
